### ISSUE TITLE
Can we cache the latest version of Drupal?

### ISSUE THREAD

**Issue by ModulesUnraveled** [kalamuna/kalaboxv1#104]
## My issue

Hey, I was on vacation this last week, and didn't have a reliable internet connection, so I had to use a cell phone as a hotspot. Since Klabox downloads the latest copy of Drupal for each install, that meant that I had to download it using my data plan. Drupal's not huge, so that wasn't a big deal, but when I was riding in the back of the van, the coverage was spotty (could even be non-existent if someone were traveling in a plane) and sometimes it errored out since it couldn't connect.

When I was using Acquia Dev Desktop, I could just copy the codebase from another installation on my computer and import it to spin up a new site. That's not possible with Kalabox at this point.
### First time installing Drupal:
1. When the user clicks the button to add a new site, Kalabox checks for a connection to d.o.
   - If there's a connection, download the latest version of Drupal and cache it for re-use later.
   - If no connection, display a message like: "Sorry, you're not connected to the internet, and Drupal has not yet been cached to your local machine. Once you are online, please try again."
### Every subsequent attempt to install Drupal:
1. When the user clicks the button to add a new site, Kalabox checks for a connection to d.o
   - If there's a connection
     -  Compare the release number (or some other identifier) with the cached version
     -  If the same, install using the cached version
     -  If different, download the latest version of Drupal and cache it for re-use later
   - If no connection, use the cached version. (It might be best to display a message that says something like "You are not connected to the internet. To install Drupal with a cached version click [Continue]. Otherwise, click cancel, connect to the internet and try again."
## Notes:
- This could be extended to include Wordpress, Backdrop etc. I'm not sure how V2 will look, but you could cache the latest version of each for users that develop on multiple CMSs
- It would probably also be best to cache the latest D7 and D8 releases when each is installed. That way, in 2 (no connection) above, the user could select the version of Drupal they need to install.

**Comment by pirog** [comment]
I think this is a great idea and would be an amazing feature! 

I think V1 is all about bug fixes and stability improvements at this point but this seems like a solid thing for V2.

**Comment by pirog** [comment]
moved https://github.com/kalabox/kalabox/issues/3
