### ISSUE TITLE
Provide some documentation for common V1 operations

### ISSUE THREAD

**Issue by kopeboy** [kalamuna/kalaboxv1#106]
I cd to my site (kalabox/www/mysite) and run drush en a_module:
"Command pm-enable needs a higher bootstrap level to run ..."

I searched online and in your wiki but couldn't find a guide to use drush, only Terminatur for a Pantheon-downloaded site. What if I want to use drush on a local site, and later upload the site to Pantheon?

Instead, drush dl a_module works

**Comment by pirog** [comment]
using drush should be the same. have you checked this out at all?
https://www.drupal.org/node/757386

**Comment by kopeboy** [comment]
Yes I checked that and tried all propesed solutions without success. There are many different posts spanning 4 years and I am not sure will apply to the Kalabox stack or my mac configuration (I had worked also with bitnami-drupal recently, maybe something is conflicting upon drush?).

Solution #4 & #6 & #7 : I cd to /Users/me/kalabox/www/mysite and run drush en mymodule there, isn't that correct? Also doing cd /Users/me/kalabox/www/mysite/sites/all/modules and drush -y en mymodule o drush en mymodule returns the same error.
Solution #8 : run those commands and/or edited 'localhost' to '127.0.0.1' in settings.php, no success.
Solution #10 : edited bash-profile like suggested, nothing changed.

Should I mention my bash.profile is like this:
. ~/.bashrc
source ~/.profile
export PATH=/usr/local/bin:$PATH
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM$
export PATH=/Applications/MAMP/Library/bin/:$PATH

and that when I run drush en mymodule the error returns also this:

Drush was attempting to connect to: 
 Drupal version         :  7.30
Site URI               :  http://default
Database driver        :  mysql
Database username      :  root
Database name          :  mysite_kala
Default theme          :  garland
Administration theme   :  garland
PHP executable         :  /usr/bin/php
PHP configuration      : 
PHP OS                 :  Darwin
Drush version          :  6.2.0
Drush configuration    : 
Drush alias files      :  /Users/me/.drush/pantheon.aliases.drushrc.php
Drupal root            :  /Users/me/kalabox/www/mysite
Site path              :  sites/default
File directory path    :  sites/default/files

**Comment by pirog** [comment]
ohhhh i see what you are doing. so you can def run drush externally on your mac but you may need to create better aliases to help facilitate that. 

generally when i run drush i will click on the ssh button the kalabox dash and run commands from there. the sites are in /var/www.

**Comment by kopeboy** [comment]
I don't have a www folder inside /var ... :O 

If I click on the SSH button what should I do next? Typing ls I can only see one of my sites which was created on Pantheon.

Thanks for you support :(

**Comment by pirog** [comment]
/var/www should be be in kalabox so you will need to click SSH first. Once
you get in do something like

```
cd /var/www
ls -lsa
```

To see call your sites and then you can just cd into a site and you should
be able to use your drush commands right there.

On Wed, Jul 30, 2014 at 4:57 PM, Lorenzo Giovenali <notifications@github.com

> wrote:
> 
> I don't have a www folder inside /var ... :O
> 
> If I click on the SSH button what should I do next? Typing ls give I can
> only see one of my sites which was created on Pantheon.
> 
> Thansk for you support :(
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kalamuna/kalabox/issues/106#issuecomment-50678692.

## 

Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by kopeboy** [comment]
Finally! Thanks a lot man! How can I send you a free beer?

**Comment by pirog** [comment]
:beer: :)

**Comment by kopeboy** [comment]
:beers:

**Comment by pirog** [comment]
3 > 1 for sure!

**Comment by pirog** [comment]
oh wait is that actually 2? i must be drunk already.

**Comment by kopeboy** [comment]
Ok, I am very sorry for having spammed in your issue queue lately. I think you really need to write some documentation for 'noobs' like me, and I would like to help but I don't think I am the right one to do it :(
Enjoy the beers (11pm here)

**Comment by pirog** [comment]
No worries! Issue reports make the project better for everybody. If you want to list maybe the top five things that would be good for us to include in documentation that would be super helpful!

**Comment by kopeboy** [comment]
I would start with:

1) How to use drush (from SSH and CDing in the right directory)

2) How to export my kalabox site (especially on Pantheon): you can download with 1 click from Pantheon but how do you upload back? And what to do if instead the site was created on Kalabox? Something has been written here http://helpdesk.getpantheon.com/customer/portal/articles/361251 but the mysql dump doesn't work out of the box

Will update when I find more difficulties :)

**Comment by pirog** [comment]
Perfect! That is all really helpful. 

I'm going to change the issue here and open to reflect the need for documentation and hopefully we can get someone on this ASAP!

**Comment by pirog** [comment]
@reynoldsalec @andrewmallis wont be around tomorrow for comday but this should be a priority and shouldnt take too long!

> I would start with:
> 
> 1) How to use drush (from SSH and CDing in the right directory)
> 
> 2) How to export my kalabox site (especially on Pantheon): you can download with 1 click from Pantheon but how do you upload back? And what to do if instead the site was created on Kalabox? Something has been written here http://helpdesk.getpantheon.com/customer/portal/articles/361251 but the mysql dump doesn't work out of the box
> 
> Will update when I find more difficulties :)

**Comment by reynoldsalec** [comment]
Temporarily assigning to @andrewmallis, let me know if you don't have time for this and I'll knock it out.

**Comment by reynoldsalec** [comment]
Provided drush instructions, need to write up some Pantheon export instructions: https://github.com/kalamuna/kalabox/wiki/Using-Kalabox-V1:-Drush---Exporting-Sites

**Comment by pirog** [comment]
Awesome! @kopeboy feel free to review all these docs we are posting to make sure they are helpful!
