### ISSUE TITLE
Kalabox fails to run when offline (without internet access)

### ISSUE THREAD

**Issue by dakala** [kalamuna/kalaboxv1#107]
Tried to start kalabox on the train this afternoon (first time of trying to do this without internet access) and couldn't. With a different vagrant set up on another machine. there's no problem with working on the train without internet connection.

What have I missed? Sorry if this isn't the right place for this issue. Thanks!

**Comment by pirog** [comment]
hmmmm. does the box just not start? does it give an error? can you paste in the log which is found at ~/.kalabox/kalastack

**Comment by dakala** [comment]
Hi @pirog. I'm afraid no logs but I think I know why. When I got home and got back online, kalabox updated itself and I suppose that wiped out the logs. Would that be a plausible reason? 

When I disconnected a while ago, kalabox started up after a brief error message (There's a problem with loading your sites list. Restarting the box may resolve it.) but all the applications started fine.

Will poke around further and try again tomorrow morning on my way to work.

**Comment by pirog** [comment]
makes sense. i didnt think the updater deleted the logs but maybe it does. certianly plausible.

the "sites list" error just pops up because the check is done too soon. if you give it like 4 seconds it usually loads up fine. that is pegged for resolution in beta9 and currently tracked here: https://github.com/kalamuna/kalabox/issues/94

**Comment by dakala** [comment]
Will report back tomorrow. Awesome work, guys!

**Comment by dakala** [comment]
After the update, it works after the known slight delay. I think this can be closed now. Thanks.

**Comment by pirog** [comment]
Sure thing! Feel free to reopen if it pops up again!
