### ISSUE TITLE
Not finding localhost site

### ISSUE THREAD

**Issue by mdyorke** [kalamuna/kalaboxv1#11]
When I click on my downloaded pantheon site in Kalabox it opens up my browser and tries to direct me to my-site.kala but is then redirected to http://www.dnsrsearch.com/index.php?origURL=http%3A//my-site.kala/&r= .  Any ideas on how to fix this?

**Comment by pirog** [comment]
Do you know who your ISP is? Sometimes they will hijack requests like this and do a search instead.

**Comment by pirog** [comment]
This has some more info
http://hackercodex.com/guide/how-to-stop-isp-dns-server-hijacking/

Some ISPs let you opt out so i would search for that. Switching your DNS to google or opendns may help as well.
http://www.howtogeek.com/howto/38793/how-to-switch-mac-os-x-to-use-opendns-or-google-dns/

**Comment by pirog** [comment]
If you are rolling with TimeWarner here is their opt out page... presumably this would be for other horrible ISPs as well. 
http://dnssearch.rr.com/prefs.php

**Comment by mdyorke** [comment]
Thanks @pirog, I will give this a try!

**Comment by pirog** [comment]
Did it work for you?

**Comment by mdyorke** [comment]
Yea! between that and cleaning up the leftover MAMP code in the Localhosts file it now runs smooth.

**Comment by pirog** [comment]
Awesome! That is great to hear. 

Going to close this for now but I wonder if there is a way for us to "fix" this for users without being too intrusive.

**Comment by ellastelter** [comment]
I had this same issue, with Cox as my ISP, and used this link to solve the issue.  I had to chose the wireless network instead of the local.  http://www.cox.com/residential/support/internet/article.cox?articleId=e14ee070-6448-11df-ccef-000000000000
