### ISSUE TITLE
Semantic versioning

### ISSUE THREAD

**Issue by pirog** [kalamuna/kalaboxv1#115]
we want to use semantic versioning for 2.x. we want this to be as automatic as possible with semantic tags being used for official releases.

**Comment by andrewmallis** [comment]
don't you mean 2.x.x?

**Comment by pirog** [comment]
i just meant 2.x as in Kalabox2 but yes eventually it would follow a 2.x.y form. I'll edit the open issue in the new repo to reflect his.
