### ISSUE TITLE
Redownloadding site issues.

### ISSUE THREAD

**Issue by asifh16** [kalamuna/kalaboxv1#117]
I cannot seem to download my site locally once ive reinstalled kalabox. Here are my steps.
- uninstalled kalabox using option 2, rm -r .vagrant.d, rm -r .kalabox
- restarted my computer
- reinstalled kalabox beta 8
- login to pantheon thru kalabox
- when i try to download the site from the latest pantheon backup it seems to download it but it then asks me again if i want to download my site from the latest backup. i click cancel. 
- If i look in my kalabox directory, all of the code is there, but when i try to view the site locally, it cannot resolve the host. Its as if the site downloaded but the kalabox isnt running although it says that it is. 

Ive tried this like 4x this morning without any luck. Any help is appreciated.

AH

**Comment by pirog** [comment]
ASIF! 

I would check out the issue over here. I'm pretty sure its the same issue you are experiencing. There are some workarounds posted for you.
https://github.com/kalamuna/kalaboxv1/issues/12

**Comment by asifh16** [comment]
Hi Mike -

Ok - I spent a couple of hours trying everything in #12. Funny thing is i dont have a ~/.kalabox/kalabox.log file to see what may be causing this problem. Should I have that? Also, one thing that i notice is right after the installation completes, the box isnt running. Then I click start, and it always says that that box wasnt ready and try back. It then turns on (status says running after a few seconds). Anyway.. This is where i am w/ this.. If you could tell me how to find the log that would be great. Thanks for your help on this.

Asif

**Comment by pirog** [comment]
It sounds to me like the box just isnt installing properly... when the installer is done you should def have the box on and ready to go. 

Sometimes, in earlier versions, vagrant would lose the VB binding ... if you run `vboxmanage list vms` what do you get?

**Comment by asifh16** [comment]
hey mike - when i run vboxmanage list vms i get:

asifs-mac-pro:.kalabox asifhabibullah$ vboxmanage list vms
"kala.1dbfeae5c34e1867bdad20e590999544.box" {f3ee424b-3312-4f2e-b911-af8dd74fb3a6}
"precise64_1402433460871_79788" {b05bf061-9631-4795-8dd7-48a0ad7d9bf6}
"kala.4745a53502d14f3e2f098f00ad73adfb.box" {8ff1e842-16dd-4c0e-90ff-2ab017ac66a0}
"precise64_1405347215644_94498" {27f6b0c7-9ada-4d08-84c5-e3cfcb5f36cf}
"kala.72b080767a7c0cc0b4124a0956e0c178.box" {071495de-1656-4cc7-a290-b2f13502eaa1}
"kala.1d89ec6295a6828ff5595fea51614691.box" {b7ff48f7-f4f0-4096-9dc8-bbccc8d2a75c}
"kala.ea2c4330bf0eb6e294a8b05577fb5fb1.box" {16b65219-507d-4ea2-b761-7259d01e336d}
"kala.3322cc75edf101ba28940d907eafbda7.box" {11b94576-5283-4e91-95fb-1a110c2dd38e}
"kala.244aa6a62d0e89d8c66c7b2047fd85e2.box" {baf05e2c-4327-458d-aa06-8cc4e9e18a79}
"kala.65ff2a57be71a6946fd4e1edafc255a0.box" {c599bd05-06ae-4f08-9239-984f8846b1b1}
"kala.6b73dc6fa62415223ada59c22d60f3b4.box" {8ea15c14-f069-4ad6-9bce-86144fadd143}
"kala.244c42e3c1be82a574015050d9657a2d.box" {5a00cc6c-58d1-4cac-b068-f659c2663439}
asifs-mac-pro:.kalabox asifhabibullah$

Asif Habibullah

Director US East Coast Operations

Computers & Structures, Inc.

TECHNOLOGY FOR A BETTER WORLD

36 West 44th Street, Suite 300

New York, NY 10036 - USA

Direct   
+1 212 575 9100 x3333

Cell      
+1 917 306 4387

Fax     
+1 212 575 1967

asif@csiamerica.com

www.csiamerica.com

On Aug 11, 2014, at 8:02 PM, Mike Pirog notifications@github.com wrote:

It sounds to me like the box just isnt installing properly... when the installer is done you should def have the box on and ready to go.

Sometimes, in earlier versions, vagrant would lose the VB binding ... if you run
vboxmanage list vms what do you get?
—
Reply to this email directly or 
view it on GitHub.

**Comment by pirog** [comment]
aha! those are a lot of kalabox. the kalabox app may be getting confused about which virtual machine is actually the right one. 

i would go into VirtualBox and delete all of these manually. Then run uninstall #2 and try installing again with a fresh slate.

**Comment by asifh16** [comment]
Ive tried everything man. I deleted all of the vm's then uninstalled using the option 2 in the uninstall tool. I removed ~/.vagrant.d, ~/.kalabox, ~/kalabox, ~/.drush/cache . Then reinstalled.. I notice the VirtualBox doenst get uninstalled when I uninstall kalabox. Should i delete that manually too? Sorry to be a pain Mike...

Thanks in advance,
Asif

**Comment by pirog** [comment]
No worries, sorry V1 is being such a C :( 

VB should def be uninstalled ... do you have the app open or maybe a VB process running behind the scenes?

**Comment by asifh16** [comment]
Lemme uninstall and try again by removing VB before reinstalling..

**Comment by asifh16** [comment]
Yeah man - no luck. This time VB did get uninstalled. it must have been all of those other VM's that were in there before.. Dunno what else i can try. Is there a log somewhere I can look at?

**Comment by pirog** [comment]
What did it do when you tried to install it after this last
clean/uninstall? log should be at `~/.kalabox/kalabox.log`

On Tue, Aug 12, 2014 at 1:58 PM, Asif Habibullah notifications@github.com
wrote:

> Yeah man - no luck. This time VB did get uninstalled. it must have been
> all of those other VM's that were in there before.. Dunno what else i can
> try. Is there a log somewhere I can look at?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kalamuna/kalaboxv1/issues/117#issuecomment-51976345.

## 

Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by asifh16** [comment]
Same thing, when the installation finishes, its stays status is "stopped". When I click start is says that the box wasnt ready, then it sits for a couple of seconds an then it says running.. then i go and login to pantheon thru the kalabox ui and try to download the site and i get the infinite loop.  I dont have that file ~/.kalabox/kalabox.log . That seems strange, right?

**Comment by pirog** [comment]
yeah that is very weird... it should immediately generate that file on
installation.

On Tue, Aug 12, 2014 at 2:02 PM, Asif Habibullah notifications@github.com
wrote:

> Same thing, when the installation finishes, its stays status is "stopped".
> When I click start is says that the box wasnt ready, then it sits for a
> couple of seconds an then it says running.. then i go and login to pantheon
> thru the kalabox ui and try to download the site and i get the infinite
> loop. I dont have that file ~/.kalabox/kalabox.log . That seems strange,
> right?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kalamuna/kalaboxv1/issues/117#issuecomment-51976855.

## 

Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by asifh16** [comment]
I also tried deleting my .ssh directory in case it couldnt create the keys for some reason. So I have my home directory mounted on an external drive that is always connected.. The previous versions of kalabox worked on this.. Could that be an issue?

**Comment by pirog** [comment]
a ha! yeah i think that could definitely be the issue. is there anyway you
can test without the external drive and see what happens?

On Tue, Aug 12, 2014 at 2:05 PM, Asif Habibullah notifications@github.com
wrote:

> I also tried deleting my .ssh directory in case it couldnt create the keys
> for some reason. So I have my home directory mounted on an external drive
> that is always connected.. The previous versions of kalabox worked on
> this.. Could that be an issue?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kalamuna/kalaboxv1/issues/117#issuecomment-51977353.

## 

Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by asifh16** [comment]
what ill do is create a new user account and see what happens.

**Comment by pirog** [comment]
perfect.

On Tue, Aug 12, 2014 at 2:44 PM, Asif Habibullah notifications@github.com
wrote:

> what ill do is create a new user account and see what happens.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kalamuna/kalaboxv1/issues/117#issuecomment-51982194.

## 

Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by asifh16** [comment]
hey mike - ok this is weird.. i created a new user redownloaded the kalabox dmg and then ran it logged in as the new user and i get this upon completion.. for some reason its still referencing my asifhabibullah user account.. STRANGE.. maybe its because i switched users from that ?  how is the installer picking up the user path?

### Kalabox Log

2014-08-13T14:10:43.949Z - info: Box initialized.
2014-08-13T14:10:43.950Z - info: Kalabox Version: 1.0-beta7
2014-08-13T14:10:43.950Z - info: Mac OS Version: 10.9.2

2014-08-13T14:10:43.950Z - info: VirtualBox Version: false
2014-08-13T14:10:43.950Z - info: Vagrant Version: false
2014-08-13T14:10:48.650Z - info: VirtualBox not installed or wrong version. Installing.
2014-08-13T14:10:48.651Z - info: User granted permission to install VirtualBox
2014-08-13T14:12:35.164Z - info: Successfully downloaded VirtualBox DMG.
2014-08-13T14:12:44.120Z - info: Successfully mounted VirtualBox DMG.
2014-08-13T14:12:58.085Z - info: VirtualBox installation complete.
2014-08-13T14:12:58.167Z - info: Successfully ejected VirtualBox DMG.
2014-08-13T14:12:58.167Z - info: Vagrant not installed or wrong version. Installing.
2014-08-13T14:12:58.167Z - info: User granted permission to install Vagrant
2014-08-13T14:13:28.274Z - info: Successfully downloaded Vagrant DMG.
2014-08-13T14:13:34.058Z - info: Successfully mounted Vagrant DMG.
2014-08-13T14:13:38.854Z - info: Vagrant installation complete.
2014-08-13T14:13:38.921Z - info: Successfully ejected Vagrant DMG.
2014-08-13T14:18:17.712Z - info: Box image downloaded.
2014-08-13T14:18:18.369Z - info: Installing Vagrant plugin vagrant-hostsupdater
2014-08-13T14:18:18.916Z - info: Kalastack downloaded
2014-08-13T14:18:18.916Z - info: Installing Vagrant plugin vagrant-hostsupdater
2014-08-13T14:18:26.389Z - info: Adding base box image to Vagrant.
2014-08-13T14:18:27.839Z - info: Wrote configuration file.
2014-08-13T14:18:27.863Z - info: Executing box spinup.
2014-08-13T14:18:27.891Z - info: Starting spinup attempt 0
2014-08-13T14:18:46.843Z - warn: Spinup attempt 0 failed with error: Command failed: NFS is reporting that your exports file is invalid. Vagrant does
this check before making any changes to the file. Please correct
the issues below and execute "vagrant reload":

exports:2: path contains non-directory or non-existent components: /Volumes/User Data/asifhabibullah/kalabox/www
exports:2: no usable directories in export entry
exports:2: using fallback (marked offline): /Volumes/User Data

2014-08-13T14:18:49.373Z - info: Starting spinup attempt 1
2014-08-13T14:19:07.976Z - warn: Spinup attempt 1 failed with error: Command failed: NFS is reporting that your exports file is invalid. Vagrant does
this check before making any changes to the file. Please correct
the issues below and execute "vagrant reload":

exports:2: path contains non-directory or non-existent components: /Volumes/User Data/asifhabibullah/kalabox/www
exports:2: no usable directories in export entry
exports:2: using fallback (marked offline): /Volumes/User Data

2014-08-13T14:19:10.473Z - info: Starting spinup attempt 2
2014-08-13T14:19:29.004Z - warn: Spinup attempt 2 failed with error: Command failed: NFS is reporting that your exports file is invalid. Vagrant does
this check before making any changes to the file. Please correct
the issues below and execute "vagrant reload":

exports:2: path contains non-directory or non-existent components: /Volumes/User Data/asifhabibullah/kalabox/www
exports:2: no usable directories in export entry
exports:2: using fallback (marked offline): /Volumes/User Data

2014-08-13T14:19:31.457Z - error: Error during installation routine: An error occurred in an async call.
cause stack is ...
  Error: Failed to spin up virtual machine after 3 attempts. Error was: Command failed: NFS is reporting that your exports file is invalid. Vagrant does
this check before making any changes to the file. Please correct
the issues below and execute "vagrant reload":

exports:2: path contains non-directory or non-existent components: /Volumes/User Data/asifhabibullah/kalabox/www
exports:2: no usable directories in export entry
exports:2: using fallback (marked offline): /Volumes/User Data

```
at eval (/private/var/folders/jt/b6r51_fd5bv2jrn317780smr0000gp/T/.org.chromium.Chromium.B7zpgC/kalabox/installer/install-utils.js:359:22)
at ChildProcess.exithandler (child_process.js:659:7)
at ChildProcess.EventEmitter.emit (events.js:101:17)
at maybeClose (child_process.js:773:16)
at Process.ChildProcess._handle.onexit (child_process.js:840:5)
```

async call history is ...
 [ { function: 'install16',
    location: '/private/var/folders/jt/b6r51_fd5bv2jrn317780smr0000gp/T/.org.chromium.Chromium.B7zpgC/kalabox/installer/installer.js:484:33',
    mapping: { description: 'tail' } } ]

**Comment by pirog** [comment]
I think kalastack uses rubys dir.home and KALABOX uses just the $HOME
environmental var straight up.

On the other user what do you get if you just run "echo $HOME" in terminal

On Wednesday, August 13, 2014, Asif Habibullah notifications@github.com
wrote:

> hey mike - ok this is weird.. i created a new user redownloaded the
> kalabox dmg and then ran it logged in as the new user and i get this upon
> completion.. for some reason its still referencing my asifhabibullah user
> account.. STRANGE.. maybe its because i switched users from that ? how is
> the installer picking up the user path?
> Kalabox Log
> 
> 2014-08-13T14:10:43.949Z - info: Box initialized.
> 2014-08-13T14:10:43.950Z - info: Kalabox Version: 1.0-beta7
> 2014-08-13T14:10:43.950Z - info: Mac OS Version: 10.9.2
> 
> 2014-08-13T14:10:43.950Z - info: VirtualBox Version: false
> 2014-08-13T14:10:43.950Z - info: Vagrant Version: false
> 2014-08-13T14:10:48.650Z - info: VirtualBox not installed or wrong
> version. Installing.
> 2014-08-13T14:10:48.651Z - info: User granted permission to install
> VirtualBox
> 2014-08-13T14:12:35.164Z - info: Successfully downloaded VirtualBox DMG.
> 2014-08-13T14:12:44.120Z - info: Successfully mounted VirtualBox DMG.
> 2014-08-13T14:12:58.085Z - info: VirtualBox installation complete.
> 2014-08-13T14:12:58.167Z - info: Successfully ejected VirtualBox DMG.
> 2014-08-13T14:12:58.167Z - info: Vagrant not installed or wrong version.
> Installing.
> 2014-08-13T14:12:58.167Z - info: User granted permission to install Vagrant
> 2014-08-13T14:13:28.274Z - info: Successfully downloaded Vagrant DMG.
> 2014-08-13T14:13:34.058Z - info: Successfully mounted Vagrant DMG.
> 2014-08-13T14:13:38.854Z - info: Vagrant installation complete.
> 2014-08-13T14:13:38.921Z - info: Successfully ejected Vagrant DMG.
> 2014-08-13T14:18:17.712Z - info: Box image downloaded.
> 2014-08-13T14:18:18.369Z - info: Installing Vagrant plugin
> vagrant-hostsupdater
> 2014-08-13T14:18:18.916Z - info: Kalastack downloaded
> 2014-08-13T14:18:18.916Z - info: Installing Vagrant plugin
> vagrant-hostsupdater
> 2014-08-13T14:18:26.389Z - info: Adding base box image to Vagrant.
> 2014-08-13T14:18:27.839Z - info: Wrote configuration file.
> 2014-08-13T14:18:27.863Z - info: Executing box spinup.
> 2014-08-13T14:18:27.891Z - info: Starting spinup attempt 0
> 2014-08-13T14:18:46.843Z - warn: Spinup attempt 0 failed with error:
> Command failed: NFS is reporting that your exports file is invalid. Vagrant
> does
> this check before making any changes to the file. Please correct
> the issues below and execute "vagrant reload":
> 
> exports:2: path contains non-directory or non-existent components:
> /Volumes/User Data/asifhabibullah/kalabox/www
> exports:2: no usable directories in export entry
> exports:2: using fallback (marked offline): /Volumes/User Data
> 
> 2014-08-13T14:18:49.373Z - info: Starting spinup attempt 1
> 2014-08-13T14:19:07.976Z - warn: Spinup attempt 1 failed with error:
> Command failed: NFS is reporting that your exports file is invalid. Vagrant
> does
> this check before making any changes to the file. Please correct
> the issues below and execute "vagrant reload":
> 
> exports:2: path contains non-directory or non-existent components:
> /Volumes/User Data/asifhabibullah/kalabox/www
> exports:2: no usable directories in export entry
> exports:2: using fallback (marked offline): /Volumes/User Data
> 
> 2014-08-13T14:19:10.473Z - info: Starting spinup attempt 2
> 2014-08-13T14:19:29.004Z - warn: Spinup attempt 2 failed with error:
> Command failed: NFS is reporting that your exports file is invalid. Vagrant
> does
> this check before making any changes to the file. Please correct
> the issues below and execute "vagrant reload":
> 
> exports:2: path contains non-directory or non-existent components:
> /Volumes/User Data/asifhabibullah/kalabox/www
> exports:2: no usable directories in export entry
> exports:2: using fallback (marked offline): /Volumes/User Data
> 
> 2014-08-13T14:19:31.457Z - error: Error during installation routine: An
> error occurred in an async call.
> cause stack is ...
> Error: Failed to spin up virtual machine after 3 attempts. Error was:
> Command failed: NFS is reporting that your exports file is invalid. Vagrant
> does
> this check before making any changes to the file. Please correct
> the issues below and execute "vagrant reload":
> 
> exports:2: path contains non-directory or non-existent components:
> /Volumes/User Data/asifhabibullah/kalabox/www
> exports:2: no usable directories in export entry
> exports:2: using fallback (marked offline): /Volumes/User Data
> 
> at eval (/private/var/folders/jt/b6r51_fd5bv2jrn317780smr0000gp/T/.org.chromium.Chromium.B7zpgC/kalabox/installer/install-utils.js:359:22)
> at ChildProcess.exithandler (child_process.js:659:7)
> at ChildProcess.EventEmitter.emit (events.js:101:17)
> at maybeClose (child_process.js:773:16)
> at Process.ChildProcess._handle.onexit (child_process.js:840:5)
> 
> async call history is ...
> [ { function: 'install16',
> location:
> '/private/var/folders/jt/b6r51_fd5bv2jrn317780smr0000gp/T/.org.chromium.Chromium.B7zpgC/kalabox/installer/installer.js:484:33',
> mapping: { description: 'tail' } } ]
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kalamuna/kalaboxv1/issues/117#issuecomment-52054900.

## 

Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by asifh16** [comment]
asifs-mac-pro:~ csiwebdeveloper$ echo $HOME
/Users/csiwebdeveloper

**Comment by asifh16** [comment]
anyway i can find out what a ruby dir.home call would return?

**Comment by pirog** [comment]
I _think_ at the end of the day dir.home uses $HOME also but you should be
able to check it by invoking ruby directly on the CLI.

Give me a sec and I'll paste the command.

On Wednesday, August 13, 2014, Asif Habibullah notifications@github.com
wrote:

> anyway i can find out what a ruby dir.home call would return?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kalamuna/kalaboxv1/issues/117#issuecomment-52083880.

## 

Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by asifh16** [comment]
OK cool. Yeah something that happens at this point is where things seem to fail.

exports:2: path contains non-directory or non-existent components: /Volumes/User Data/asifhabibullah/kalabox/www

**Comment by asifh16** [comment]
Is there somewhere on my system that that other home directory is being saved and read from? Like it shouldnt be referencing that at all as this is a totally new user.

**Comment by pirog** [comment]
not on the kalabox side... i think the issue is with the dir.home directive in ruby which explains the error you are getting. 

I would try making this change in your `Vagrantfile` which lives at `~/.kalabox/kalastack` 
https://github.com/kalamuna/kalastack/commit/d7f313ce3311797f995ae62b269790c4ac15ee6e

**Comment by pirog** [comment]
yup! and that part is the only part that uses dir.home (since its part of
kalastack and not kalabox)... i _think_ switching to just invoking $HOME
directly should solve your issue but im not sure what implications this
would have for other users...

On Wed, Aug 13, 2014 at 11:07 AM, Asif Habibullah notifications@github.com
wrote:

> OK cool. Yeah something that happens at this point is where things seem to
> fail.
> 
> exports:2: path contains non-directory or non-existent components:
> /Volumes/User Data/asifhabibullah/kalabox/www
> 
> —
> 
> Reply to this email directly or view it on GitHub
> https://github.com/kalamuna/kalaboxv1/issues/117#issuecomment-52086822.

## 

Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by asifh16** [comment]
ok ill test it shortly.. thanks man.

Asif Habibullah

Director US East Coast Operations

Computers & Structures, Inc.

TECHNOLOGY FOR A BETTER WORLD

36 West 44th Street, Suite 300

New York, NY 10036 - USA

Direct   
+1 212 575 9100 x3333

Cell      
+1 917 306 4387

Fax     
+1 212 575 1967

asif@csiamerica.com

www.csiamerica.com

On Aug 13, 2014, at 2:39 PM, Mike Pirog notifications@github.com wrote:
yup! and that part is the only part that uses dir.home (since its part of

kalastack and not kalabox)... i _think_ switching to just invoking $HOME 
directly should solve your issue but im not sure what implications this 
would have for other users... 
On Wed, Aug 13, 2014 at 11:07 AM, Asif Habibullah notifications@github.com

wrote:

**Comment by pirog** [comment]
sure thing. ping me back to let me know the results!

On Wed, Aug 13, 2014 at 11:43 AM, Asif Habibullah notifications@github.com
wrote:

> ok ill test it shortly.. thanks man.
> 
> Asif Habibullah
> 
> Director US East Coast Operations
> 
> Computers & Structures, Inc.
> 
> TECHNOLOGY FOR A BETTER WORLD
> 
> 36 West 44th Street, Suite 300
> 
> New York, NY 10036 - USA
> 
> Direct
> +1 212 575 9100 x3333
> 
> Cell
> +1 917 306 4387
> 
> Fax
> +1 212 575 1967
> 
> asif@csiamerica.com
> 
> www.csiamerica.com
> 
> On Aug 13, 2014, at 2:39 PM, Mike Pirog notifications@github.com wrote:
> yup! and that part is the only part that uses dir.home (since its part of
> 
> kalastack and not kalabox)... i _think_ switching to just invoking $HOME
> directly should solve your issue but im not sure what implications this
> would have for other users...
> On Wed, Aug 13, 2014 at 11:07 AM, Asif Habibullah <
> notifications@github.com>
> 
> wrote:
> 
> > OK cool. Yeah something that happens at this point is where things seem
> > to
> > fail.
> > 
> > exports:2: path contains non-directory or non-existent components:
> > /Volumes/User Data/asifhabibullah/kalabox/www
> > 
> > —
> > 
> > Reply to this email directly or view it on GitHub
> > https://github.com/kalamuna/kalaboxv1/issues/117#issuecomment-52086822.
> > 
> > ## 
> > 
> > Cheers,
> > Mike Pirog
> > Kalamuna www.kalamuna.com
> > —
> > Reply to this email directly or
> > view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kalamuna/kalaboxv1/issues/117#issuecomment-52091862.

## 

Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by asifh16** [comment]
OK. So that got me passed the installation issue. The installation completes now w/ the new user that i created. But now im again stuck in the infinite loop.. If i look in the ~/kalabox.log this is the error that i have appended to the end of that file now in there now. This comes right after the installation complete line...

2014-08-13T19:55:22.628Z - warn: An error occurred in an async call.
cause stack is ...
  Error: Command failed: Drush command terminated abnormally due to an unrecoverable error.       [error]
Error: require_once(): Failed opening required
'/var/www/csi-america/sites/default/files/private/mailsystem/MimeMailSystem__SmtpMailSystem.mail.inc'
(include_path='.:/usr/share/php:/usr/share/pear') in
/var/www/csi-america/includes/bootstrap.inc, line 3209
The external command could not be executed due to an application         [error]
error.

```
at ChildProcess.exithandler (child_process.js:661:12)
at ChildProcess.EventEmitter.emit (events.js:101:17)
at maybeClose (child_process.js:773:16)
at Socket.eval (child_process.js:994:11)
at Socket.EventEmitter.emit (events.js:98:17)
at Pipe.eval [as close] (net.js:459:12)
```

async call history is ...
 [ { function: 'buildSite2',
    location: '/private/var/folders/jt/b6r51_fd5bv2jrn317780smr0000gp/T/.org.chromium.Chromium.Umq40Z/kalabox/vm/sites-manager.js:106:75',
    mapping: { description: 'tail' } } ]

**Comment by asifh16** [comment]
Hi Mike - Did u see my comment above? Strange, right?

**Comment by pirog** [comment]
Yes. This looks like its an issue with your particular drupal site. 

My guess here is your site is trying to bootstrap before you have pulled your files down. You must have a module or entry in `settings.php` that is referencing this during build which is causing the problem. 

Do you know why you have `mailsystem/MimeMailSystem__SmtpMailSystem.mail.inc` stored in your files directory instead of under version control in somewhere like `sites/all/libraries`? 

I'm guessing the issue here is more about drupal site config than kalabox, but will def help if i can!

**Comment by labboy0276** [comment]
@pirog @asifh16 OK we had to build the mime/html/smtp stuff in the private folders due to the templates they needed not working normally.  There is some docs out there to do this.

However, this doesnt help us here.  What I going to do is install the habitat module, disable all mail stuff on dev and test and have him retry pulling down

**Comment by pirog** [comment]
that works.

i'm somewhat skeptical that this stuff has to live in `/files/private` ...
that seems very weird to me but i dont know enough about it to definitively
say it is wrong.

On Fri, Aug 15, 2014 at 3:01 PM, John Ouellet notifications@github.com
wrote:

> @pirog https://github.com/pirog @asifh16 https://github.com/asifh16
> OK we had to build the mime/html/smtp stuff in the private folders due to
> the templates they needed not working normally. There is some docs out
> there to do this.
> 
> However, this doesnt help us here. What I going to do is install the
> habitat module, disable all mail stuff on dev and test and have him retry
> pulling down
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kalamuna/kalaboxv1/issues/117#issuecomment-52365502.

## 

Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by labboy0276** [comment]
@pirog yes it was weird and getting to work right with this special template was weird

@asifh16 Try now, I would crush your site and pull from latest dev

**Comment by asifh16** [comment]
I'm not at work and that problem happens on my work computer. I'll try to check over the weekend but it not it's not gonna be til Friday as I'm heading to Cali Sunday for the week. . 

Asif Habibullah
Director US East Coast Operations
Computers & Structures, Inc.
TECHNOLOGY FOR A BETTER WORLD
36 West 44th Street, Suite 300
New York, NY 10036 - USA
Direct   +1 212 575 9100 x3333
Cell      +1 917 306 4387
Fax     +1 212 575 1967
asif@csiamerica.com
www.csiamerica.com

On Aug 15, 2014, at 6:15 PM, "John Ouellet" notifications@github.com wrote:

@pirog yes it was weird and getting to work right with this special template was weird
@asifh16 Try now, I would crush your site and pull from latest dev
—
Reply to this email directly or 
view it on GitHub.

**Comment by labboy0276** [comment]
@pirog @asifh16 just as a fyi, i crushed my csi site and rebuilt it with the new settings and all was well.  I do remember this happening and @pirog id correct that bootstrap is starting and checking for the private folder which has the mail stuff in it.  Since we dont pull files normally in a box spinout, this caused it to crash.  I remember I just put the files dir in my box and it was ok.  However, adding in habitat and disabling all the mail modules on all enivornments but live alliviated the error above.

@asifh16 can test, but it seems good

**Comment by pirog** [comment]
this is great and thanks for the help @labboy0276... i would also def
encourage to see if you can find a way to use this functionality in a more
drupal friendly way ie using libraries api or at least having the file
somewhere in version control.

On Sat, Aug 16, 2014 at 7:00 AM, John Ouellet notifications@github.com
wrote:

> @pirog https://github.com/pirog @asifh16 https://github.com/asifh16
> just as a fyi, i crushed my csi site and rebuilt it with the new settings
> and all was well. I do remember this happening and @pirog
> https://github.com/pirog id correct that bootstrap is starting and
> checking for the private folder which has the mail stuff in it. Since we
> dont pull files normally in a box spinout, this caused it to crash. I
> remember I just put the files dir in my box and it was ok. However, adding
> in habitat and disabling all the mail modules on all enivornments but live
> alliviated the error above.
> 
> @asifh16 https://github.com/asifh16 can test, but it seems good
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kalamuna/kalaboxv1/issues/117#issuecomment-52393866.

## 

Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by asifh16** [comment]
I wont be able to test this on the machine that im having the problems on til Friday.. Im gonna make sure it works on my machine here today. Will let u know soon. Thanks you so much for all of ur help @pirog @labboy0276 .

**Comment by asifh16** [comment]
@pirog @labboy0276 my site is now working well w/ the kalabox.. thanks for all of your help. Asif
