### ISSUE TITLE
Stuck in initial install

### ISSUE THREAD

**Issue by nadavoid** [kalamuna/kalaboxv1#118]
My kalabox.log has this, and never gets any farther. This is after clicking the "Box Me" button. I let it try for several hours today on a good internet connection. (I've also tried: reinstalled vagrant and virtual box, an uninstalled a previous version of kalabox.)

```
2014-08-15T05:22:41.608Z - info: Kalabox Version: 1.0-beta7
2014-08-15T05:22:41.609Z - info: Mac OS Version: 10.9.4

2014-08-15T05:22:41.609Z - info: VirtualBox Version: 4.3.14r95030

2014-08-15T05:22:41.609Z - info: Vagrant Version: Vagrant 1.6.3

2014-08-15T05:22:43.701Z - info: Existing VirtualBox installation, version 4.3.14
2014-08-15T05:22:43.702Z - info: Existing Vagrant installation, version 1.6.3
2014-08-15T05:22:43.702Z - info: Vagrant not installed or wrong version. Installing.
```

**Comment by nadavoid** [comment]
Certainly something odd is that it says kalabox version 1.0-beta7, but the downloaded disk image was kalabox-1.0-beta8.dmg

**Comment by pirog** [comment]
The issue is we don't support Vagrant 1.5+ at this point. Your best bet is to run the uninstall,tool that comes with the DMG and select option 2. This will uninstall VB/Vagrant and allow kalabox to use the preferred versions.

**Comment by nadavoid** [comment]
Thanks for the suggestion @pirog. That seems to have worked. It's installing and downloading stuff now.

**Comment by pirog** [comment]
Awesome! Did that end up working for you?

On Fri, Aug 15, 2014 at 1:48 PM, David Lanier notifications@github.com
wrote:

> Thanks for the suggestion @pirog https://github.com/pirog. That seems
> to have worked. It's installing and downloading stuff now.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kalamuna/kalaboxv1/issues/118#issuecomment-52356017.

## 

Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by nadavoid** [comment]
It sure did. Thanks @pirog!
