### ISSUE TITLE
publickey issue

### ISSUE THREAD

**Issue by allenfear** [kalamuna/kalaboxv1#121]
I've run into two issues after having installed Kalabox for the first time. The first is that running git pull against my pantheon environments results in a "Permission denied (password,publickey)" error. I see a key at ~/.ssh/terminatur.id_rsa.pub and also see a new terminatur key showing up in my pantheon dashboard. Should this just work, or is there some setup I've overlooked?

I'm also seeing another, likely unrelated, issue, but since it's also permissions-related, here it is: one of the downloaded sites loads fine, but another can't seem to connect to the db and loads with this error: "PDOException: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) in lock_may_be_available() (line 167 of /var/www/ets2/includes/lock.inc)." There's a Kalabox environment wrapper with the db credentials in the settings.php that the installation process seems to have stuck in there, so I'm not sure why it's not allowing access.

**Comment by pirog** [comment]
I think https://github.com/kalamuna/kalaboxv1/issues/69 may be the key to this first issue

the second: is your database empty?

**Comment by allenfear** [comment]
Thanks for the quick response! I resolved the key issue by simply renaming the files and updated #69 with the fix.

Nope, the db isn't empty. I also made a fresh backup and imported that from pantheon and got the same result. The site loads fine on pantheon:
http://dev-ets2.gotpantheon.com/

**Comment by pirog** [comment]
Awesome! Great to know! 

do you have any extra stuff in your settings.php that may be specific to pantheon that are causing chaos when you download your site? that can be another problem area. for those things its good to wrap them in something like 

```
if (defined('PANTHEON_ENVIRONMENT')) {
  // my pantheon specific settings.php things
}
```

You could also exclude things based on whether you are not on KALABOX with

```
if (!isset($_SERVER['KALABOX'])) { 
   // settings.php things that happen outside of kalabox
} 
```

**Comment by allenfear** [comment]
Figured it out. For some reason terminatur generated a db string for this site instead of an array:

```
if (isset($_SERVER['KALABOX']) &&  $_SERVER['KALABOX'] === 'on') { 
  // DB String 
  $db_url = 'mysql://root:password@localhost:3306/mysite_kala';
}
```

For my working Kalabox sites I noticed I had an array, so I pasted that in, reset the db name and boomshakalaka.

```
if (isset($_SERVER['KALABOX']) &&  $_SERVER['KALABOX'] === 'on') { 
  // DB Array and some common conf 
  $databases['default']['default'] = array( 
    'driver' => 'mysql',
    'database' => 'mysite_kala', 
    'username' => 'root',
    'password' => 'password',
    'host' => 'localhost',
    'port' => '3306',
    'prefix' => '',
  );
}
```

Not sure if this is an issue with the way terminatur generates the db settings or just something wonky with my settings file, but it doesn't seem to be a Kalabox issue, which is working great. Thanks for your help!
