### ISSUE TITLE
Where should I put my alias file so that I can use sql-sync etc.?

### ISSUE THREAD

**Issue by ModulesUnraveled** [kalamuna/kalaboxv1#124]
Just want to know where I should put my drush alias file. I didn't see one in ~/.drush so I wasn't sure if that was the right place.

**Comment by pirog** [comment]
your pantheon aliases should get put in /etc/kalastack (i _think_) and they get refreshed whenever you login/logut/reffresh the sites list. 

you should be able to put other aliases in ~/.drush and have them work just fine!

**Comment by ModulesUnraveled** [comment]
Awesome. Thanks!
