### ISSUE TITLE
Downloading Drupal 6 sites from Pantheon

### ISSUE THREAD

**Issue by steveixa** [kalamuna/kalaboxv1#13]
I noticed when I pulled a Drupal 6 site from Pantheon the settings.php file was configured for a Drupal 7 site. Kalabox reports that the download was successful but when you visit the site it prompts you to do a fresh install.

To fix it I just changed the database settings in the settings.php to use the Drupal 6 syntax and all was good.

**Comment by pirog** [comment]
This is an issue with terminatur. I've opened an issue there. 
https://github.com/kalamuna/terminatur/issues/22

**Comment by reynoldsalec** [comment]
Addressed in issue over in Terminatur, @steveixa check that out for more info.
