### ISSUE TITLE
Allow users to Skip Virtualbox version requirement

### ISSUE THREAD

**Issue by gremy** [kalamuna/kalaboxv1#15]
It would be very helpful to allow users to skip the Virtualbox version dependency because many experienced developers already have the latest Vagrant and Virtualbox installed and Kalastack runs just fine on the latest version.
This issue might influence a lot of developers to not proceed with the installation of Kalabox.

![screen shot 2014-06-19 at 14 09 51](https://cloud.githubusercontent.com/assets/1007285/3333691/4e774594-f7f6-11e3-91aa-8cd06ce5441f.png)

**Comment by pirog** [comment]
Let's find out what the lowest possible version of virtualbox is that is required by KB and set things there. That will make this less annoying to everyone.

**Comment by gremy** [comment]
The problem is not with having a lower version of Virtualbox, it is with having a newer version.
I have a newer version of Virtualbox and I cannot install Kalabox beacuse is not the exact version that is configured in the installer.
I am however running Kalastack separately without any problem.

My proposal is to have a button there to ignore the requirement and just attempt to install Kalabox with current version of Virtualbox.

**Comment by pirog** [comment]
Yes. What i am saying is let's find the minimum required version and whitelist everything above that. I want to simplify things here. 

If you have a newer version i think we just prompt the user to let them know that it's not tested with their version and ask whether they want to proceed as you suggest.

**Comment by gremy** [comment]
Sounds like a good plan.

**Comment by gremy** [comment]
I guess that my problem with the latest virtualbox is solved by.
https://github.com/gremy/kalabox/commit/c2bc580c3c39c591887b975236ecc4fa0a17af65#comments

**Comment by pirog** [comment]
awesome! love it when issues are heavily multicolinear
