### ISSUE TITLE
Kalaboxv2 problem during install on latest osx (10.11.6)

### ISSUE THREAD

**Issue by kscheirer** [kalamuna/kalaboxv1#161]
Everything seems good until `./postinstall: Host does not exist: "Kalabox2"`, I think that means the docker image was not created? The Kalabox portion of /var/log/install.log:

Aug  9 17:34:14 Karls-MacBook-Pro Installer[1229]: LSExceptions [0x7f9339c0b220] loaded
Aug  9 17:34:14 Karls-MacBook-Pro Installer[1229]: @(#)PROGRAM:Install  PROJECT:Install-1000
Aug  9 17:34:14 Karls-MacBook-Pro Installer[1229]: @(#)PROGRAM:Installer  PROJECT:Installer-853
Aug  9 17:34:14 Karls-MacBook-Pro Installer[1229]: Hardware: MacBookPro10,1 @ 2.60 GHz (x 8), 16384 MB RAM
Aug  9 17:34:14 Karls-MacBook-Pro Installer[1229]: Running OS Build: Mac OS X 10.11.6 (15G31)
Aug  9 17:34:14 Karls-MacBook-Pro Installer[1229]: Env: __CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0
Aug  9 17:34:14 Karls-MacBook-Pro Installer[1229]: Env: TMPDIR=/var/folders/wd/840tv5tj3zlcms3tbxbcwbym0000gn/T/
Aug  9 17:34:14 Karls-MacBook-Pro Installer[1229]: Env: HOME=/Users/karl
Aug  9 17:34:14 Karls-MacBook-Pro Installer[1229]: Env: SHELL=/bin/bash
Aug  9 17:34:14 Karls-MacBook-Pro Installer[1229]: Env: SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.YuEGY3mSZK/Listeners
Aug  9 17:34:14 Karls-MacBook-Pro Installer[1229]: Env: Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.SKhENAuTtw/Render
Aug  9 17:34:14 Karls-MacBook-Pro Installer[1229]: Env: PATH=/usr/bin:/bin:/usr/sbin:/sbin
Aug  9 17:34:14 Karls-MacBook-Pro Installer[1229]: Env: LOGNAME=karl
Aug  9 17:34:14 Karls-MacBook-Pro Installer[1229]: Env: XPC_SERVICE_NAME=com.apple.xpc.launchd.oneshot.0x10000010.Installer
Aug  9 17:34:14 Karls-MacBook-Pro Installer[1229]: Env: COMMAND_MODE=unix2003
Aug  9 17:34:14 Karls-MacBook-Pro Installer[1229]: Env: USER=karl
Aug  9 17:34:14 Karls-MacBook-Pro Installer[1229]: Env: XPC_FLAGS=0x0
Aug  9 17:34:14 Karls-MacBook-Pro Installer[1229]: Kalabox 0.13.0-beta.4 Installation Log
Aug  9 17:34:14 Karls-MacBook-Pro Installer[1229]: Opened from: /Volumes/Kalabox/KalaboxInstaller.pkg
Aug  9 17:34:14 Karls-MacBook-Pro Installer[1229]: Product archive /Volumes/Kalabox/KalaboxInstaller.pkg trustLevel=100
Aug  9 17:34:15 Karls-MacBook-Pro Installer[1229]: JS: Hardware architecture detected: x86_64
Aug  9 17:34:15 Karls-MacBook-Pro Installer[1229]: JS: OS version detected: 10.11.6
Aug  9 17:34:15 Karls-MacBook-Pro Installer[1229]: JS: result:true
Aug  9 17:34:22 Karls-MacBook-Pro Installer[1229]: InstallerStatusNotifications plugin loaded
Aug  9 17:34:24 Karls-MacBook-Pro Installer[1229]: LSExceptions [0x7f9339c0b220] unloaded
Aug  9 17:34:26 Karls-MacBook-Pro Installer[1229]: Administrator authorization granted.
Aug  9 17:34:26 Karls-MacBook-Pro Installer[1229]: ================================================================================
Aug  9 17:34:26 Karls-MacBook-Pro Installer[1229]: User picked Standard Install
Aug  9 17:34:26 Karls-MacBook-Pro Installer[1229]: Choices selected for installation:
Aug  9 17:34:26 Karls-MacBook-Pro Installer[1229]:  Install: "Kalabox"
Aug  9 17:34:26 Karls-MacBook-Pro Installer[1229]:  Install: "Kalabox %KBOX_VERSION%"
Aug  9 17:34:26 Karls-MacBook-Pro Installer[1229]:      KalaboxInstaller.pkg#kbox.pkg : io.kalabox.pkg.kalabox : 0.13.0-beta.4
Aug  9 17:34:26 Karls-MacBook-Pro Installer[1229]: ================================================================================
Aug  9 17:34:26 Karls-MacBook-Pro Installer[1229]: It took 0.00 seconds to summarize the package selections.
Aug  9 17:34:26 Karls-MacBook-Pro Installer[1229]: -[IFDInstallController(Private) _buildInstallPlanReturningError:]: location = file://localhost
Aug  9 17:34:26 Karls-MacBook-Pro Installer[1229]: -[IFDInstallController(Private) _buildInstallPlanReturningError:]: file://localhost/Volumes/Kalabox/KalaboxInstaller.pkg#kbox.pkg
Aug  9 17:34:26 Karls-MacBook-Pro Installer[1229]: Set authorization level to root for session
Aug  9 17:34:26 Karls-MacBook-Pro Installer[1229]: Will use PK session
Aug  9 17:34:26 Karls-MacBook-Pro Installer[1229]: Using authorization level of root for IFPKInstallElement
Aug  9 17:34:26 Karls-MacBook-Pro Installer[1229]: Starting installation:
Aug  9 17:34:26 Karls-MacBook-Pro Installer[1229]: Configuring volume "Macintosh HD"
Aug  9 17:34:26 Karls-MacBook-Pro Installer[1229]: Preparing disk for local booted install.
Aug  9 17:34:26 Karls-MacBook-Pro Installer[1229]: Free space on "Macintosh HD": 37.09 GB (37091987456 bytes).
Aug  9 17:34:26 Karls-MacBook-Pro Installer[1229]: Create temporary directory "/var/folders/wd/840tv5tj3zlcms3tbxbcwbym0000gn/T//Install.1229VpVhtd"
Aug  9 17:34:26 Karls-MacBook-Pro Installer[1229]: IFPKInstallElement (1 packages)
Aug  9 17:34:26 Karls-MacBook-Pro installd[343]: PackageKit: Adding client PKInstallDaemonClient pid=1229, uid=501 (/System/Library/CoreServices/Installer.app/Contents/MacOS/Installer)
Aug  9 17:34:26 Karls-MacBook-Pro Installer[1229]: PackageKit: Enqueuing install with framework-specified quality of service (utility)
Aug  9 17:34:26 Karls-MacBook-Pro installd[343]: PackageKit: ----- Begin install -----
Aug  9 17:34:26 Karls-MacBook-Pro installd[343]: PackageKit: request=PKInstallRequest <1 packages, destination=/>
Aug  9 17:34:26 Karls-MacBook-Pro installd[343]: PackageKit: packages=(
        "PKLeopardPackage file://localhost/Volumes/Kalabox/KalaboxInstaller.pkg#kbox.pkg"
    )
Aug  9 17:34:27 Karls-MacBook-Pro installd[343]: PackageKit: Extracting file://localhost/Volumes/Kalabox/KalaboxInstaller.pkg#kbox.pkg (destination=/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/6020EA04-51EC-47BE-8D35-A24B2D17C0F3.activeSandbox/Root/Applications, uid=0)
Aug  9 17:34:31 Karls-MacBook-Pro installd[343]: PackageKit: prevent user idle system sleep
Aug  9 17:34:31 Karls-MacBook-Pro installd[343]: PackageKit: suspending backupd
Aug  9 17:34:31 Karls-MacBook-Pro installd[343]: PackageKit: Using trashcan path /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/PKInstallSandboxTrash/6020EA04-51EC-47BE-8D35-A24B2D17C0F3.sandboxTrash for sandbox /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/6020EA04-51EC-47BE-8D35-A24B2D17C0F3.activeSandbox
Aug  9 17:34:31 Karls-MacBook-Pro installd[343]: PackageKit: Shoving /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/6020EA04-51EC-47BE-8D35-A24B2D17C0F3.activeSandbox/Root (1 items) to /
Aug  9 17:34:31 Karls-MacBook-Pro install_monitor[1233]: Temporarily excluding: /Applications, /Library, /System, /bin, /private, /sbin, /usr
Aug  9 17:34:34 Karls-MacBook-Pro installd[343]: PackageKit: Executing script "./postinstall" in /private/tmp/PKInstallSandbox.b85lPC/Scripts/io.kalabox.pkg.kalabox.eABXY4
Aug  9 17:34:36 Karls-MacBook-Pro installd[343]: ./postinstall: Host does not exist: "Kalabox2"
Aug  9 17:34:36 Karls-MacBook-Pro installd[343]: ./postinstall: Regenerate TLS machine certs?  Warning: this is irreversible. (y/n): Regenerating TLS certificates
Aug  9 17:34:36 Karls-MacBook-Pro installd[343]: ./postinstall: Host does not exist: "Kalabox2"
Aug  9 17:34:36 --- last message repeated 1 time ---
Aug  9 17:34:36 Karls-MacBook-Pro installd[343]: ./postinstall: TLS configuration is invalid - make sure your DOCKER_TLS_VERIFY and DOCKER_CERT_PATH are set correctly.
Aug  9 17:34:36 Karls-MacBook-Pro installd[343]: ./postinstall: You might need to run `eval "$(docker-machine env default)"`
Aug  9 17:34:36 Karls-MacBook-Pro installd[343]: ./postinstall: Something went wrong installing core Docker images
Aug  9 17:34:36 Karls-MacBook-Pro install_monitor[1233]: Re-included: /Applications, /Library, /System, /bin, /private, /sbin, /usr
Aug  9 17:34:37 Karls-MacBook-Pro installd[343]: PackageKit: releasing backupd
Aug  9 17:34:37 Karls-MacBook-Pro installd[343]: PackageKit: allow user idle system sleep
Aug  9 17:34:37 Karls-MacBook-Pro installd[343]: PackageKit: Install Failed: Error Domain=PKInstallErrorDomain Code=112 "An error occurred while running scripts from the package “KalaboxInstaller.pkg”." UserInfo={NSFilePath=./postinstall, NSURL=file://localhost/Volumes/Kalabox/KalaboxInstaller.pkg#kbox.pkg, PKInstallPackageIdentifier=io.kalabox.pkg.kalabox, NSLocalizedDescription=An error occurred while running scripts from the package “KalaboxInstaller.pkg”.} {
        NSFilePath = "./postinstall";
        NSLocalizedDescription = "An error occurred while running scripts from the package \U201cKalaboxInstaller.pkg\U201d.";
        NSURL = "file://localhost/Volumes/Kalabox/KalaboxInstaller.pkg#kbox.pkg";
        PKInstallPackageIdentifier = "io.kalabox.pkg.kalabox";
    }
Aug  9 17:34:37 Karls-MacBook-Pro installd[343]: PackageKit: Running idle tasks
Aug  9 17:34:37 Karls-MacBook-Pro Installer[1229]: install:didFailWithError:Error Domain=PKInstallErrorDomain Code=112 "An error occurred while running scripts from the package “KalaboxInstaller.pkg”." UserInfo={NSFilePath=./postinstall, NSURL=file://localhost/Volumes/Kalabox/KalaboxInstaller.pkg#kbox.pkg, PKInstallPackageIdentifier=io.kalabox.pkg.kalabox, NSLocalizedDescription=An error occurred while running scripts from the package “KalaboxInstaller.pkg”.}
Aug  9 17:34:37 Karls-MacBook-Pro installd[343]: PackageKit: Removing client PKInstallDaemonClient pid=1229, uid=501 (/System/Library/CoreServices/Installer.app/Contents/MacOS/Installer)
Aug  9 17:34:37 Karls-MacBook-Pro installd[343]: PackageKit: Done with sandbox removals
Aug  9 17:34:37 Karls-MacBook-Pro installd[343]: PackageKit: Sandbox /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/A26B40E3-87AE-4210-926F-79103284B8AC.sandbox: relevance 1539
Aug  9 17:34:37 Karls-MacBook-Pro Installer[1229]: Install failed: The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.
Aug  9 17:34:37 Karls-MacBook-Pro Installer[1229]: IFDInstallController 39D77A30 state = 8
Aug  9 17:34:37 Karls-MacBook-Pro Installer[1229]: Displaying 'Install Failed' UI.
Aug  9 17:34:37 Karls-MacBook-Pro Installer[1229]: 'Install Failed' UI displayed message:'The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.'.

**Comment by pirog** [comment]
@kscheirer i think you are looking for https://github.com/kalabox/kalabox.

**Comment by kscheirer** [comment]
Yup, sorry!
