### ISSUE TITLE
Allow terminal choice or find what the user sets as default.

### ISSUE THREAD

**Issue by bassettsj** [kalamuna/kalaboxv1#18]
The SSH button launches Terminal on my Mac. I use iTerm 2, can we change the logic for how it launches that app.

**Comment by fluxsauce** [comment]
```
open ssh://username@host
```

will use the default SSH client, which can include iTerm. Tested by using Terminal and the above command, and it spawned a new iTerm tab.

**Comment by andrewmallis** [comment]
+1

**Comment by pirog** [comment]
I know a bunch of people who would be very pleased by this feature. Let's make it happen.

**Comment by pirog** [comment]
@fluxsauce looking at this further we have to run "vagrant ssh" ... not sure if i want to bypass the wrapping function here. 

good news is this should be a sinch in V2 :)

**Comment by kellybell** [comment]
+++++ _I_ would be VERY pleased to see this happen!!! +++++

**Comment by pirog** [comment]
Execute the following command:

vagrant ssh-config | grep IdentityFile  | awk '{print $2}'

Then you should get something like:

/<somepath>/<username>/.vagrant.d/insecure_private_key

Now you can ssh into the VM by:

ssh 127.0.0.1 -p 2222  -i /<somepath>/<username>/.vagrant.d/insecure_private_key -l vagrant

**Comment by kellybell** [comment]
From where in my file system do I execute this command? I tried at root, at
usr/bin/vagrant, at ~, and in ~/kalabox. All show the same error:

kelly-macbookpro:kbell 0 [06-30 17:45] ~/kalabox

! vagrant ssh-config | grep IdentityFile | awk '{print $2}'

A Vagrant environment is required to run this command. Run `vagrant init`

to set one up in this directory, or change to a directory with a

Vagrantfile and try again.

Kelly Bell
Founder and CTO
Gotham City Drupal
917-446-1555

**Comment by pirog** [comment]
dont worry about any of this :)
i just pasted it in here for the record

On Mon, Jun 30, 2014 at 5:47 PM, Kelly Bell notifications@github.com
wrote:

> From where in my file system do I execute this command? I tried at root,
> at
> usr/bin/vagrant, at ~, and in ~/kalabox. All show the same error:
> 
> kelly-macbookpro:kbell 0 [06-30 17:45] ~/kalabox
> 
> ! vagrant ssh-config | grep IdentityFile | awk '{print $2}'
> 
> A Vagrant environment is required to run this command. Run `vagrant init`
> 
> to set one up in this directory, or change to a directory with a
> 
> Vagrantfile and try again.
> 
> Kelly Bell
> Founder and CTO
> Gotham City Drupal
> 917-446-1555
> 
> On Mon, Jun 30, 2014 at 5:05 PM, Mike Pirog notifications@github.com
> wrote:
> 
> > Execute the following command:
> > 
> > vagrant ssh-config | grep IdentityFile | awk '{print $2}'
> > 
> > Then you should get something like:
> > 
> > ///.vagrant.d/insecure_private_key
> > 
> > Now you can ssh into the VM by:
> > 
> > ssh 127.0.0.1 -p 2222 -i ///.vagrant.d/insecure_private_key -l vagrant
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/kalamuna/kalabox/issues/18#issuecomment-47602770.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kalamuna/kalabox/issues/18#issuecomment-47605337.

## 

Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by pirog** [comment]
As long as you have set iTerm (or whatevs) as the default ssh handler correctly this should work. Would encourage someone to build from head to test.

**Comment by kellybell** [comment]
How do we update if we already have Kv1b6 running?

**Comment by pirog** [comment]
It's funny you ask that... i am just updating the docs to reflect how to
run from source :)

On Mon, Jun 30, 2014 at 8:54 PM, Kelly Bell notifications@github.com
wrote:

> How do we update if we already have Kv1b6 running?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kalamuna/kalabox/issues/18#issuecomment-47614494.

## 

Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by pirog** [comment]
https://github.com/kalamuna/kalabox/wiki/Contributing-to-Kalabox

**Comment by kellybell** [comment]
And... I googled it because I wasn't sure I was right about this, but I don't know that you CAN set iTerm (or any app besides Terminal) to be the default shell app - but maybe if we know exactly which file type is being accessed to open it... is it <pre>myfile.sh</pre>

**Comment by pirog** [comment]
which is why i said "set to default ssh handler" and not default shell app :)
http://apple.stackexchange.com/questions/28938/set-iterm2-as-the-ssh-url-handler

**Comment by kellybell** [comment]
Excellent - I had already done this, so hopefully it will "just work", once I can update my Box. Thanks @pirog !

**Comment by pirog** [comment]
Which you _could_ do now by building from source if you wanted :)
https://github.com/kalamuna/kalabox/wiki/Contributing-to-Kalabox

**Comment by kellybell** [comment]
I _could_, and I _will_, but I am now on my 20th straight hour at the kb, and I'm ready to jump off a bridge, except I'm too tired. I'll catch y'all tomorrow, ladies!

**Comment by pirog** [comment]
curtsy
