### ISSUE TITLE
move to using github flow for collaboration

### ISSUE THREAD

**Issue by bassettsj** [kalamuna/kalaboxv1#22]
> [Github Flow](http://scottchacon.com/2011/08/31/github-flow.html)

**Comment by pirog** [comment]
+1 

I've revoked all push access except for @reynoldsalec and myself to help enforce this for now. @reynoldsalec lets try to follow this like we are on kalatheme. it a great model. 

@bassettsj, as soon as you get more familiar with the goals, etc of the project we can add you as an "owner" as well so you can partake in the great merging. Your experience with JS will be a huge bonus and i would encourage you to help evaluate all pull requests from that perspective regardless.
