### ISSUE TITLE
JShint refactor fun?

### ISSUE THREAD

**Issue by bassettsj** [kalamuna/kalaboxv1#26]
Would be good to get the JSHint checks to pass, but that means some boring refactoring to get it done, but I think enforcing a coding style would be healthy. Anyone want to take this one on?

**Comment by pirog** [comment]
I've got a vague but likely comprehensive task that should probably include this in #52 but will likely need your expertise when i start to implement!

**Comment by pirog** [comment]
@bassettsj im going to move this to V2 and cut our losses on V1

**Comment by bassettsj** [comment]
Okay.
