### ISSUE TITLE
Update Doesn't Work

### ISSUE THREAD

**Issue by reynoldsalec** [kalamuna/kalaboxv1#29]
The current update process (the notification for updating) doesn't appear to work. DO NOT UPDATE YOUR KALABOX until we've resolved that, it could cause problems after update.

**Comment by reynoldsalec** [comment]
It appears that updating can delete your kalastack files. To repair this...
1. Copy the folders .kalabox and .vagrant from your kalastack directory to a safe place (say your Desktop)
   
   `cp -r $HOME/.kalabox/kalastack/.kalabox $HOME/Desktop && cp -r $HOME/.kalabox/kalastack/.vagrant $HOME/Desktop` 
2. Delete (or otherwise remove) the $HOME/.kalabox/kalastack directory
   
   `rm -r $HOME/.kalabox/kalastack`
3. Clone kalastack from github: 
   
   `git clone git@github.com:kalamuna/kalastack.git $HOME/.kalabox/kalastack`
4. Copy the .kalabox and .vagrant folders back from your safe place to kalastack:
   
   `cp -r $HOME/Desktop/.kalabox $HOME/.kalabox/kalastack && cp -r $HOME/Desktop/.vagrant $HOME/.kalabox/kalastack`

After doing this, you should be able to start up Kalabox as normal.

**Comment by reynoldsalec** [comment]
There are two problems here:

One is that in Kalabox's update.js, it anticipates the updated Kalastack to be located at KALASTACK_BASE_URL + configuration['kalastack_version']), which is "http://files.kalamuna.com/3.0-beta4". When I uploaded Kalastack to that location, the update "worked."

HOWEVER, the second issue is that when Kalastack is rebuilt from the new version, it deletes the old .kalabox and .vagrant files to spin up a new VirtualBox. This means that a user's old databases and other information will be lost. Not sure how to solve this without telling people to just re-install Kalabox; we need to either fix the updater.js file to not delete these crucial files, or just remove the update functionality all together for now.

**Comment by pirog** [comment]
Given that 1.0 is near end of life I say we remove update func completely.
How many other updates to kalastack are we going to have?

On Thursday, June 26, 2014, reynoldsalec notifications@github.com wrote:

> There are two problems here:
> 
> One is that in Kalabox's update.js, it anticipates the updated Kalastack
> to be located at KALASTACK_BASE_URL + configuration['kalastack_version']),
> which is "http://files.kalamuna.com/3.0-beta4". When I uploaded Kalastack
> to that location, the update "worked."
> 
> HOWEVER, the second issue is that when Kalastack is rebuilt from the new
> version, it deletes the old .kalabox and .vagrant files to spin up a new
> VirtualBox. This means that a user's old databases and other information
> will be lost. Not sure how to solve this without telling people to just
> re-install Kalabox; we need to either fix the updater.js file to not delete
> these crucial files, or just remove the update functionality all together
> for now.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kalamuna/kalabox/issues/29#issuecomment-47255789.

## 

Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by reynoldsalec** [comment]
Down with that; just figured out that the update keeps the .kalabox and .vagrant (see the KEEP_FILES constant in updater.js), so now that I've uploaded the kalastack file, the update should work as expected. New issue for removing update is #30.

**Comment by reynoldsalec** [comment]
Going to close for now, will handle support requests as they come in.
