### ISSUE TITLE
Having problems installing (again) see error below

### ISSUE THREAD

**Issue by kellybell** [kalamuna/kalaboxv1#34]
### Kalabox Log

2014-06-30T20:07:36.741Z - info: Box initialized.
2014-06-30T20:07:36.743Z - info: Kalabox Version: 1.0-beta6
2014-06-30T20:07:36.743Z - info: Mac OS Version: 10.9.3

2014-06-30T20:07:36.743Z - info: VirtualBox Version: 4.3.8r92456

2014-06-30T20:07:36.743Z - info: Vagrant Version: Vagrant 1.4.3

2014-06-30T20:07:37.858Z - info: Existing VirtualBox installation, version 4.3.8
2014-06-30T20:07:37.859Z - info: Existing Vagrant installation, version 1.4.3
2014-06-30T20:08:02.686Z - info: Existing VirtualBox installation, version 4.3.8
2014-06-30T20:08:02.686Z - info: Existing Vagrant installation, version 1.4.3
2014-06-30T20:08:03.550Z - info: Existing VirtualBox installation, version 4.3.8
2014-06-30T20:08:03.551Z - info: Existing Vagrant installation, version 1.4.3
2014-06-30T20:18:07.132Z - info: Existing VirtualBox installation, version 4.3.8
2014-06-30T20:18:07.134Z - info: Existing Vagrant installation, version 1.4.3
2014-06-30T20:18:09.904Z - info: Existing VirtualBox installation, version 4.3.8
2014-06-30T20:18:09.905Z - info: Existing Vagrant installation, version 1.4.3
2014-06-30T20:18:09.965Z - info: Existing VirtualBox installation, version 4.3.8
2014-06-30T20:18:09.965Z - info: Existing Vagrant installation, version 1.4.3
2014-06-30T20:25:48.999Z - info: Box image downloaded.
2014-06-30T20:25:55.014Z - info: Installing Vagrant plugin vagrant-hostsupdater
2014-06-30T20:25:59.472Z - info: Kalastack downloaded
2014-06-30T20:25:59.472Z - info: Installing Vagrant plugin vagrant-hostsupdater
2014-06-30T20:26:26.559Z - info: Wrote configuration file.
2014-06-30T20:26:26.626Z - info: Executing box spinup.
2014-06-30T20:26:26.718Z - info: Starting spinup attempt 0
2014-06-30T20:29:20.575Z - error: Error during installation routine: An error occurred in an async call.
cause stack is ...
  undefined
async call history is ...
 [ { function: 'install6',
    location: '/private/var/folders/8s/clzrjqvn7nz7p496s61nh5k40000gp/T/.org.chromium.Chromium.S0Wrco/kalabox/installer/installer.js:386:58',
    mapping: { description: 'tail' } } ]
2014-06-30T20:29:20.624Z - error: Error during installation routine: An error occurred in an async call.
cause stack is ...
  undefined
async call history is ...
 [ { function: 'install6',
    location: '/private/var/folders/8s/clzrjqvn7nz7p496s61nh5k40000gp/T/.org.chromium.Chromium.S0Wrco/kalabox/installer/installer.js:386:58',
    mapping: { description: 'tail' } } ]

**Comment by pirog** [comment]
It just does not like you. Anything in error log beyond this?

**Comment by pirog** [comment]
This is stopping when it tries to download the kalabox basebox. What do you have in ~/.kalabox/ ?

**Comment by kellybell** [comment]
I ran the uninstall tool first, per usual - so, nothing.

Kelly Bell
Founder and CTO
Gotham City Drupal
917-446-1555

**Comment by kellybell** [comment]
I'm going to try the whole process again, I guess. But step 1 is ALWAYS
ALWAYS ALWAYS uninstall. I never forget.

Kelly Bell
Founder and CTO
Gotham City Drupal
917-446-1555

**Comment by pirog** [comment]
Uninstall.tool doesnt delete old baseboxes so it might still be in there.
100% sure that dir is empty?

On Mon, Jun 30, 2014 at 1:43 PM, Kelly Bell notifications@github.com
wrote:

> I ran the uninstall tool first, per usual - so, nothing.
> 
> Kelly Bell
> Founder and CTO
> Gotham City Drupal
> 917-446-1555
> 
> On Mon, Jun 30, 2014 at 1:42 PM, Mike Pirog notifications@github.com
> wrote:
> 
> > This is stopping when it tries to download the kalabox basebox. What do
> > you have in ~/.kalabox/ ?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/kalamuna/kalabox/issues/34#issuecomment-47584140.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kalamuna/kalabox/issues/34#issuecomment-47584254.

## 

Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by kellybell** [comment]
kelly-macbookpro:kbell 0 [06-30 13:05] ~

! cd ~/.kalabox/

kelly-macbookpro:kbell 0 [06-30 13:47] ~/.kalabox

! ls -a

.  ..

Kelly Bell
Founder and CTO
Gotham City Drupal
917-446-1555

**Comment by kellybell** [comment]
No go (again):

### Kalabox Log

2014-06-30T20:50:45.535Z - info: Box initialized.
2014-06-30T20:50:45.536Z - info: Kalabox Version: 1.0-beta6
2014-06-30T20:50:45.537Z - info: Mac OS Version: 10.9.3

2014-06-30T20:50:45.537Z - info: VirtualBox Version: false
2014-06-30T20:50:45.537Z - info: Vagrant Version: false
2014-06-30T20:50:53.783Z - info: VirtualBox not installed or wrong version.
Installing.
2014-06-30T20:50:53.784Z - info: User granted permission to install
VirtualBox
2014-06-30T20:52:12.040Z - info: Successfully downloaded VirtualBox DMG.
2014-06-30T20:52:34.721Z - info: Successfully mounted VirtualBox DMG.
2014-06-30T20:56:16.541Z - info: VirtualBox installation complete.
2014-06-30T20:56:19.224Z - info: Successfully ejected VirtualBox DMG.
2014-06-30T20:56:19.225Z - info: Vagrant not installed or wrong version.
Installing.
2014-06-30T20:56:19.226Z - info: User granted permission to install Vagrant
2014-06-30T20:56:40.497Z - info: Successfully downloaded Vagrant DMG.
2014-06-30T20:56:46.684Z - info: Successfully mounted Vagrant DMG.
2014-06-30T20:57:17.092Z - info: Vagrant installation complete.
2014-06-30T20:57:17.561Z - info: Successfully ejected Vagrant DMG.
2014-06-30T21:00:30.248Z - info: Box image downloaded.
2014-06-30T21:00:33.216Z - info: Installing Vagrant plugin
vagrant-hostsupdater
2014-06-30T21:00:52.936Z - info: Kalastack downloaded
2014-06-30T21:00:52.940Z - info: Installing Vagrant plugin
vagrant-hostsupdater
2014-06-30T21:01:15.899Z - info: Wrote configuration file.
2014-06-30T21:01:16.085Z - info: Executing box spinup.
2014-06-30T21:01:16.219Z - info: Starting spinup attempt 0
2014-06-30T21:07:13.554Z - warn: Spinup attempt 0 failed with error:
Command failed: NFS is reporting that your exports file is invalid. Vagrant
does
this check before making any changes to the file. Please correct
the issues below and execute "vagrant reload":

exports:3: path contains non-directory or non-existent components:
/Users/kbell/kalabox/drush
exports:3: no usable directories in export entry
exports:3: using fallback (marked offline): /

2014-06-30T21:07:34.181Z - info: Starting spinup attempt 1
2014-06-30T21:13:11.408Z - warn: Spinup attempt 1 failed with error:
Command failed: NFS is reporting that your exports file is invalid. Vagrant
does
this check before making any changes to the file. Please correct
the issues below and execute "vagrant reload":

exports:3: path contains non-directory or non-existent components:
/Users/kbell/kalabox/drush
exports:3: no usable directories in export entry
exports:3: using fallback (marked offline): /

2014-06-30T21:13:25.050Z - info: Starting spinup attempt 2
2014-06-30T21:18:32.596Z - warn: Spinup attempt 2 failed with error:
Command failed: NFS is reporting that your exports file is invalid. Vagrant
does
this check before making any changes to the file. Please correct
the issues below and execute "vagrant reload":

exports:3: path contains non-directory or non-existent components:
/Users/kbell/kalabox/drush
exports:3: no usable directories in export entry
exports:3: using fallback (marked offline): /

2014-06-30T21:18:54.190Z - error: Error during installation routine: An
error occurred in an async call.
cause stack is ...
  Error: Failed to spin up virtual machine after 3 attempts. Error was:
Command failed: NFS is reporting that your exports file is invalid. Vagrant
does
this check before making any changes to the file. Please correct
the issues below and execute "vagrant reload":

exports:3: path contains non-directory or non-existent components:
/Users/kbell/kalabox/drush
exports:3: no usable directories in export entry
exports:3: using fallback (marked offline): /

```
at eval
```

(/private/var/folders/8s/clzrjqvn7nz7p496s61nh5k40000gp/T/.org.chromium.Chromium.0Sf5Nr/kalabox/installer/install-utils.js:359:22)
    at ChildProcess.exithandler (child_process.js:659:7)
    at ChildProcess.EventEmitter.emit (events.js:101:17)
    at maybeClose (child_process.js:773:16)
    at Socket.eval (child_process.js:994:11)
    at Socket.EventEmitter.emit (events.js:98:17)
    at Pipe.eval [as close](net.js:459:12)
async call history is ...
 [ { function: 'install16',
    location:
'/private/var/folders/8s/clzrjqvn7nz7p496s61nh5k40000gp/T/.org.chromium.Chromium.0Sf5Nr/kalabox/installer/installer.js:480:33',
    mapping: { description: 'tail' } } ]

Kelly Bell
Founder and CTO
Gotham City Drupal
917-446-1555

**Comment by pirog** [comment]
Got further this time... maybe just a network hiccup on the box download. The relevant pieces of the error seem to be:

Command failed: NFS is reporting that your exports file is invalid. Vagrant 
does 
this check before making any changes to the file. Please correct 
the issues below and execute "vagrant reload": 

exports:3: path contains non-directory or non-existent components: 
/Users/kbell/kalabox/drush 
exports:3: no usable directories in export entry 
exports:3: using fallback (marked offline): / 

Can you post your /etc/exports here?

**Comment by kellybell** [comment]
# VAGRANT-BEGIN: 259c9f99-f6fd-491b-8fc1-f7256c69a8cf

"/Users/kbell/kalabox/www" 192.168.42.10 -mapall=502:20
"/Users/kbell/kalabox/drush" 192.168.42.10 -mapall=502:20

# VAGRANT-END: 259c9f99-f6fd-491b-8fc1-f7256c69a8cf

# VAGRANT-BEGIN: 502 3a8fea33-6868-4808-a3f7-5d4f32f06680

"/Users/kbell/kalabox/www" 1.3.3.7 -alldirs -mapall=502:20

# VAGRANT-END: 502 3a8fea33-6868-4808-a3f7-5d4f32f06680

# VAGRANT-BEGIN: 502 418342bf-123d-4388-add8-bdb0686c2e75

"/Users/kbell/kalabox/www" 1.3.3.7 -alldirs -mapall=502:20

# VAGRANT-END: 502 418342bf-123d-4388-add8-bdb0686c2e75

# VAGRANT-BEGIN: 502 393baba3-c67d-4008-b96d-b64ad2cd60a9

"/Users/kbell/kalabox/www" 1.3.3.7 -alldirs -mapall=502:20

# VAGRANT-END: 502 393baba3-c67d-4008-b96d-b64ad2cd60a9

Kelly Bell
Founder and CTO
Gotham City Drupal
917-446-1555

**Comment by pirog** [comment]
Are you using these for anything?

**Comment by kellybell** [comment]
No - I didn't install them even, AFAIK

Kelly Bell
Founder and CTO
Gotham City Drupal
917-446-1555

**Comment by pirog** [comment]
i could just delete everything in that file and try the installer again.
Shouldnt need to uninstall!

On Mon, Jun 30, 2014 at 2:40 PM, Kelly Bell notifications@github.com
wrote:

> No - I didn't install them even, AFAIK
> 
> Kelly Bell
> Founder and CTO
> Gotham City Drupal
> 917-446-1555
> 
> On Mon, Jun 30, 2014 at 2:34 PM, Mike Pirog notifications@github.com
> wrote:
> 
> > Are you using these for anything?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/kalamuna/kalabox/issues/34#issuecomment-47590273.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kalamuna/kalabox/issues/34#issuecomment-47590983.

## 

Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by kellybell** [comment]
I'd say this was pure PEBCAK, except I'm following the exact same process
each time and getting different results each time:
1. uninstall (option 2 - nuke all)
2. Copy to Applications folder
3. Launch and follow all permissions, etc. directions

The first time Kalabox just crashed - no warning, no error messages
The second-third times I logged the errors here.

There's just not that much for me to fuck up BCAK...

Kelly Bell
Founder and CTO
Gotham City Drupal
917-446-1555

**Comment by kellybell** [comment]
ok I'll try that.

Kelly Bell
Founder and CTO
Gotham City Drupal
917-446-1555

**Comment by kellybell** [comment]
Note that even without deleting the Vagrant installer file, this is taking
forever. I've literally been trying to install nonstop since you first sent
me the link today. Surely this shouldn't be taking this long, right?

I'm at "kalaboxing" right now (after emptying the etc/exports file).

Kelly Bell
Founder and CTO
Gotham City Drupal
917-446-1555

**Comment by pirog** [comment]
What is the vagrant installer file? Not sure what you mean by that. 

We benchmark the total install at around 5-15 minutes from starting with nothing to full spin up depending on how fast your internet is. Obviously it will take longer if you have issues that we need to troubleshoot.

How long has it been "kalaboxing"?

If you want to try and "kalabox manually" and see any potential errors during spin up i would go into ~/.kalabox/kalastack and run vagrant destroy and then vagrant up.

**Comment by kellybell** [comment]
It's still 'boxing', but I checked the exports file and now it has:

# VAGRANT-BEGIN: 502 590ae2db-5b1b-4377-acdc-bb85e8311edb

"/Users/kbell/kalabox/www" 1.3.3.7 -alldirs -mapall=502:20

# VAGRANT-END: 502 590ae2db-5b1b-4377-acdc-bb85e8311edb

There is an option in the uninstaller that asks about nuking the Virtual
Box (not vagrant - sorry) installer file - this last time I chose not to
nuke it, since it's just a download.

Kelly Bell
Founder and CTO
Gotham City Drupal
917-446-1555

**Comment by kellybell** [comment]
ie:

Do you want to remove the Kalabox VirtualBox image? This won’t impact
anything on your system, but may make future Kalabox installs take longer.
(y/n)

n

Kelly Bell
Founder and CTO
Gotham City Drupal
917-446-1555

**Comment by kellybell** [comment]
But even so, it's been a lot longer than 15 minutes. I guess if this fails
I'll do the manual box and see if that yields any useful info.

Kelly Bell
Founder and CTO
Gotham City Drupal
917-446-1555

**Comment by pirog** [comment]
That's good re: exports. That looks much more normal and healthy. Got it on uninstall.tool, that option was added just for people whose downloads are corrupted. 

Yeah it def shouldn't take that long. I'd give it 10 minutes more and then try to manually do it and see what happens.

This thread is a great example of why V2 is critical: no NFS/exports, no basebox download, no vagrant. no actual spin up.

**Comment by kellybell** [comment]
I may not have time to keep on this today, if this last one fails. The
client coder for whom I was asking for a key earlier - I don't know if he's
having any trouble or not. I'll check on him tomorrow. He hasn;t said
anything about having trouble, but then he may not even have started it
yet.

Kelly Bell
Founder and CTO
Gotham City Drupal
917-446-1555

**Comment by pirog** [comment]
Most people have been getting through the install OK. 
The biggest "error" we are seeing right now is
https://github.com/kalamuna/kalabox/issues/12

**Comment by kellybell** [comment]
Yes, I see. Well, it's likely I'll have that one too if it IS related to
fast_404 because ALL my settings.php files in Pantheon have that set to
run. If it's the key problem, then I'm sure I'll have that one too. :)

Kelly Bell
Founder and CTO
Gotham City Drupal
917-446-1555

**Comment by pirog** [comment]
I'm pretty @reynoldsalec solved the issue related to fast 404 in the latest terminatur release which is in beta6 but there are other things that cause funk here that we are investigating. It doesnt blow the whole thing up but its a little annoying cause you need to restart the box. 

Another +1 for V2: config in ENV following the 12 factor app model.

**Comment by kellybell** [comment]
HOLY CRAP I think it WORKED this time!!
SO here's the ONLY thing I did differently this time: I changed the file
permissions on etc/exports to read/write EVERYWHERE. I don't KNOW if that
fixed it, but it was locked down before. Since it's the only change I made
though, I'm suspicious that was the problem.

Kelly Bell
Founder and CTO
Gotham City Drupal
917-446-1555

**Comment by pirog** [comment]
NFS is my personal Satan

**Comment by pirog** [comment]
So you have the DASH and everything up and running?

**Comment by kellybell** [comment]
Working on it now.

Kelly Bell
Founder and CTO
Gotham City Drupal
917-446-1555

**Comment by kellybell** [comment]
Next feature ask from me would be if we can run the Box on an external
drive instead of the main drive... I know that's a lot to ask, but it would
sure make things better for me.

I'm authenticated and refreshing my sites from the P dash right now.

Kelly Bell
Founder and CTO
Gotham City Drupal
917-446-1555

**Comment by kellybell** [comment]
(not ALL my sites, obi - just two of them - to use as tests)

Kelly Bell
Founder and CTO
Gotham City Drupal
917-446-1555

**Comment by kellybell** [comment]
Yes. Docker-b-rad. I can't WAIT for K2!!!

Kelly Bell
Founder and CTO
Gotham City Drupal
917-446-1555

**Comment by pirog** [comment]
@kellybell we've got a ticket internally for V2 that discusses portable boxes.... like physically portable ie USB, etc.

**Comment by pirog** [comment]
Whoops! did i just say that publicly?

**Comment by kellybell** [comment]
OMG OMG OMG OMG!!!!! Where do I sign up in my ecstatic ++++++++++ -ness?

Kelly Bell
Founder and CTO
Gotham City Drupal
917-446-1555

**Comment by kellybell** [comment]
So... I seem to be having some trouble downloading sites. I select "create
backup and dl" and DON'T select files... and it just errors out (after a
very long time) and asks me again after it fails (so far). Thoughts? Should
I open a SEPARATE ticket for this problem?

Kelly Bell
Founder and CTO
Gotham City Drupal
917-446-1555

**Comment by kellybell** [comment]
This is what it looks like while it's thinking. Then the green clouds turn
grey again and I get a popup asking me again how I want to get my files/db.

Kelly Bell
Founder and CTO
Gotham City Drupal
917-446-1555

**Comment by pirog** [comment]
Yeah this is #12 ... if you restart the box i think the site shows up fine.

**Comment by kellybell** [comment]
I've also tried re-trying using "use latest backup" with "no files" and
same thing happens.

Kelly Bell
Founder and CTO
Gotham City Drupal
917-446-1555

**Comment by pirog** [comment]
I think it actually gets your stuff fine its just a weird problem at the end. @reynoldsalec and I are going to focus on #12 tonight and issue a hotfix for the app which should be a drag and drop update.

**Comment by kellybell** [comment]
Oh. Weird - that's not what the issue sounded like to me. I'm a moron.

I restarted and the sites are there, as advertised.

Thanks!

Kelly Bell
Founder and CTO
Gotham City Drupal
917-446-1555

**Comment by kellybell** [comment]
SWEEEEEET!! Sounds like so much fun... though I can imagine you guys would
so much rather be working on v2 right now...

Kelly Bell
Founder and CTO
Gotham City Drupal
917-446-1555

**Comment by kellybell** [comment]
This may be unrelated (and/or may be #12 ), but I restarted as directed after downloading, to pick up the sites, and while they have their thumbnails now and they LOOK as if they're there, when I click any of the downloaded clouds or their links I get "Safari cannot find the server" error. 

All the Box status' are green, and when I look in phpmyadmin I see all the databases are listed there, and they seem to be the right sizes and with content intact.

Thoughts?

PS - Thanks for the "engage"ment!

**Comment by pirog** [comment]
guessing the thing is looping before entries can be added to /etc/hosts. do
you have SITENAME.kala in there?

On Mon, Jun 30, 2014 at 7:31 PM, Kelly Bell notifications@github.com
wrote:

> This may be unrelated (and/or may be #12
> https://github.com/kalamuna/kalabox/issues/12 ), but I restarted as
> directed after downloading, to pick up the sites, and while they have their
> thumbnails now and they LOOK as if they're there, when I click any of the
> downloaded clouds or their links I get "Safari cannot find the server"
> error.
> 
> All the Box status' are green, and when I look in phpmyadmin I see all the
> databases are listed there, and they seem to be the right sizes and with
> content intact.
> 
> Thoughts?
> 
> PS - Thanks for the "engage"ment!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kalamuna/kalabox/issues/34#issuecomment-47610690.

## 

Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by kellybell** [comment]
Yes - it seems to be generating the site name .kala just fine, for both the
link and the thumbnail, and the URL is also listed in the Safari error.

Kelly Bell
Founder and CTO
Gotham City Drupal
917-446-1555

**Comment by kellybell** [comment]
Also, it happens VERY fast - almost instantaneous (the failure).

**Comment by pirog** [comment]
I would open up a new issue for this :)

**Comment by kellybell** [comment]
will do.

**Comment by kellybell** [comment]
done #36

**Comment by kellybell** [comment]
Do we know definitively is this was fixed by changing the permissions on the /etc/exports file?

**Comment by pirog** [comment]
seems that way but i'd keep it open for awhile. There were a few strange
things in here so i'd def let it sit a bit.

On Mon, Jun 30, 2014 at 7:53 PM, Kelly Bell notifications@github.com
wrote:

> Do we know definitively is this was fixed by changing the permissions on
> the /etc/exports file?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kalamuna/kalabox/issues/34#issuecomment-47611812.

## 

Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by kellybell** [comment]
BOOM!
The latest dev build worked perfectly - without a hitch. 

I uninstalled using option #2 and "no", then reinstalled the latest dev build. It took about 12 minutes, and the sites downloaded and launched in browser without restart or any other problems.

C O N G R A T U L A T I O N S ! ! ! ! !

**Comment by pirog** [comment]
That's what a late night and some whiskey can do :)

CLOSE THIS ISSUE :)

On Tuesday, July 1, 2014, Kelly Bell notifications@github.com wrote:

> BOOM!
> The latest dev build worked perfectly - without a hitch.
> 
> I uninstalled using option #2 https://github.com/kalamuna/kalabox/pull/2
> and "no", then reinstalled the latest dev build. It took about 12 minutes,
> and the sites downloaded and launched in browser without restart or any
> other problems.
> 
> C O N G R A T U L A T I O N S ! ! ! ! !
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kalamuna/kalabox/issues/34#issuecomment-47685988.

## 

Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by kellybell** [comment]
BOOM!
