### ISSUE TITLE
Failure to spawn files/code backups on pantheon

### ISSUE THREAD

**Issue by kellybell** [kalamuna/kalaboxv1#35]
This may not be a real bug, but I went to my P dashboard and the two backups that I requested (via the clone site in Kalabox feature) failed. The db backups worked, but files and code both failed. I guess it's really only a cosmetic thing, but it might give people the wrong impression...

Cheers,
K

**Comment by pirog** [comment]
If you mean you are asking pantheon to "make a new backup" when you select what database to use then yes that is what is supposed to happen. You are only backing up the database.

**Comment by kellybell** [comment]
I understand, but... I'm commenting on how users might perceive that
negatively, because it says "failed". If there is a way for it to make ALL
the pieces of the backups go ahead and work, but have Kalabox NOT CARE that
they've been created (i.e. move right on once it has the DB)  --  or
alternately,  find a way to ask for a DB backup without Pantheon seeing it
as a failure -- I'm just suggesting that it looks bad, as-is.

Kelly Bell
Founder and CTO
Gotham City Drupal
917-446-1555

**Comment by pirog** [comment]
might be something to ping @joshkoenig on. maybe there is a way in terminus
to only export a database vs doing a full backup but for only one
component.
i dont really think this is a big deal.

On Mon, Jun 30, 2014 at 7:34 PM, Kelly Bell notifications@github.com
wrote:

> I understand, but... I'm commenting on how users might perceive that
> negatively, because it says "failed". If there is a way for it to make ALL
> the pieces of the backups go ahead and work, but have Kalabox NOT CARE
> that
> they've been created (i.e. move right on once it has the DB) -- or
> alternately, find a way to ask for a DB backup without Pantheon seeing it
> as a failure -- I'm just suggesting that it looks bad, as-is.
> 
> Kelly Bell
> Founder and CTO
> Gotham City Drupal
> 917-446-1555
> 
> On Mon, Jun 30, 2014 at 7:21 PM, Mike Pirog notifications@github.com
> wrote:
> 
> > If you mean you are asking pantheon to "make a new backup" when you
> > select
> > your data option then yes that is what is supposed to happen. You are
> > only
> > backing up the database.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/kalamuna/kalabox/issues/35#issuecomment-47610292.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kalamuna/kalabox/issues/35#issuecomment-47610852.

## 

Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com
