### ISSUE TITLE
Site downloads error

### ISSUE THREAD

**Issue by kellybell** [kalamuna/kalaboxv1#36]
This may be unrelated (and/or may be #12 ), but I restarted as directed after downloading, to pick up the sites, and while they have their thumbnails now and they LOOK as if they're there, when I click any of the downloaded clouds or their links I get "Safari cannot find the server" error.

All the Box status' are green, and when I look in phpmyadmin I see all the databases are listed there, and they seem to be the right sizes and with content intact.

The links are properly generated (.kala) and the error happens VERY fast. The DB is certainly not being engaged.

Thoughts?

**Comment by pirog** [comment]
SSH inside of the box and verify you have a vhost for that site. They should be at /etc/kalastack/vhosts/sites-available

**Comment by kellybell** [comment]
Nope. It's empty.

Kelly Bell
Founder and CTO
Gotham City Drupal
917-446-1555

**Comment by pirog** [comment]
can you go into /var/www/SITENAME and verify your code is there? seems like your DB made it down ok?

**Comment by kellybell** [comment]
yes. All code is present.

<code>
vagrant@kala:/var/www/bkh$ ls -a
.              html5.html          misc                    scripts
..             includes            modules                 sites
authorize.php  index.php           nodes_centers.php       themes
cck.php        INSTALL.mysql.txt   nodes_neighborhood.php  update.php
CHANGELOG.txt  INSTALL.pgsql.txt   nodes.php               UPGRADE.txt
COPYRIGHT.txt  install.php         PATCHES.txt             web.config
cron.php       INSTALL.sqlite.txt  phpinfo.php             xmlrpc.php
.git           INSTALL.txt         profiles
.gitignore     LICENSE.txt         README.txt
.htaccess      MAINTAINERS.txt     robots.txt
</code>

**Comment by kellybell** [comment]
do you use a hash or checksum of some kind to confirm when the db has fully downloaded?

**Comment by pirog** [comment]
OK. so prob vhost rage likely because #12 doesnt let it get that far. Here is a default vhost file

```
server
{
    server_name mysite.kala;
    root /var/www/mysite;

    client_max_body_size 100M;
    fastcgi_read_timeout 1800;

    index index.php;

    # No reading git files
    location ~ /\.git {
        autoindex on;
    }

    # Protect /private (for private code)
    location ~ ^/private/ {
      return 403;
    }

    # Protect /sites/default/files/private (for private files)
    location ~ ^/sites/default/files/private/ {
      return 403;
    }

    # Protect /sites/default/config (for configuration)
    location ~ ^/sites/default/config/ {
      return 403;
    }

    location / {
        try_files $uri $uri/ @cleanurl;
    }

    location @cleanurl {
        rewrite ^/(.*)$ /index.php?q=$1 last;
    }

    location ~ \.php$ {
        try_files $uri =404;

        include fastcgi_params;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_pass unix:/tmp/php-fpm.sock;
    }

    location ~ /\.ht {
         deny all;
    }
}
```

I would copy this in to `/etc/kalastack/vhosts/sites-available/mysite` and symlink it into `/etc/kalastack/vhosts/sites-enabled` with `ln -s /etc/kalastack/vhosts/sites-available/mysite /etc/kalastack/vhosts/sites-enabled/mysite` and then restart nginx  `sudo service nginx restart`

**Comment by pirog** [comment]
At the end of the day your DB is just being downloaded with
_drush_download_file

On Mon, Jun 30, 2014 at 8:01 PM, Kelly Bell notifications@github.com
wrote:

> do you use a hash or checksum of some kind to confirm when the db has
> fully downloaded?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kalamuna/kalabox/issues/36#issuecomment-47612170.

## 

Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by pirog** [comment]
Obviously you need to replace mysite with your actual site name here too :)

**Comment by kellybell** [comment]
hrm (db dl).

There isn't even a kalastack dir at etc. (/etc/kalastack doesn't exist)

If I have to do this for every site I'll lose my mind, so I'm going to pick this back up tomorrow.

**Comment by kellybell** [comment]
'mysite' has to be edited inside the vhosts file as well, so yeah - I'd rather start over when #12 is fixed rather than edit all this, honestly.

**Comment by pirog** [comment]
@kellybell fair enough but wanted to post it for others.

/etc/kalastack should be in your box not on your mac

**Comment by kellybell** [comment]
sure - I started out at vagrant@kala but popped myself out of it when I went back to look and missed it, sorry.

So yes - the vhost files are present:

<pre>
vagrant@kala:/etc/kalastack/vhosts/sites-available$ ls -a
.  ..  bkh  iberdrola  mysite  scc-v2
</pre>

**Comment by kellybell** [comment]
and the contents of the vhost files are as expected.

**Comment by pirog** [comment]
so you have entries in /etc/hosts on your mac for these sites? and they have vhosts? and they have code and data?

**Comment by kellybell** [comment]
No - all the other times I checked I was in ssh in the Box - it was just
that last time I popped out somehow and didn't catch that I had done.

Kelly Bell
Founder and CTO
Gotham City Drupal
917-446-1555

**Comment by pirog** [comment]
ok so you don't have /etc/hosts entries? Spell it out for me @kellybell

**Comment by kellybell** [comment]
No - I do. I have everything you've asked me about so far, and they're all
where they're supposed to be. But the sites don't load in the browser.
Sorry for the earlier confusion on vhosts.

Kelly Bell
Founder and CTO
Gotham City Drupal
917-446-1555

**Comment by pirog** [comment]
Ok. That is good to know and obviously strange since those are the things you need. We will look into that more. In the meantime you can enjoy this
https://github.com/kalamuna/kalabox/issues/18

**Comment by pirog** [comment]
This should be resolved in the latest dev
