### ISSUE TITLE
Question: Git GUI (ie Tower) integration FAQ?

### ISSUE THREAD

**Issue by kellybell** [kalamuna/kalaboxv1#40]
Is there a FAQ on integrating Tower (http://git-tower.com) with Kalabox?

**Comment by pirog** [comment]
There is not.

On Tue, Jul 1, 2014 at 6:20 PM, Kelly Bell notifications@github.com wrote:

> Is there a FAQ on integrating Tower (http://git-tower.com) with Kalabox?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kalamuna/kalabox/issues/40.

## 

Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by kellybell** [comment]
Welllllll... There needs to be :)

On Jul 1, 2014, at 20:00, Mike Pirog notifications@github.com wrote:

There is not.

On Tue, Jul 1, 2014 at 6:20 PM, Kelly Bell notifications@github.com
wrote:

> Is there a FAQ on integrating Tower (http://git-tower.com) with Kalabox?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kalamuna/kalabox/issues/40.

## 

Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by andrewmallis** [comment]
Tower is git client like smartgit or sourcetree or many other such applications that provide a window the the git version history,  and allow the user to perform operations like branching, merging, comparing differences, or committing their code upstream.

To access any repository, these apps just need to access the .git directory of a project. Since Kalabox connects to your sites via the guest's local filesystem, there is no need to integrate at all. Just point tower to ~/kalabox/www/myproject. It does not matter wether Kalabox is running or not.

**Comment by kellybell** [comment]
yes and no. it needs to be integrated because i want the app to see
pantheon as the upstream and the box as local  that's not easy to do the
way the box is set up.

Kelly Bell
Founder and CTO
Gotham City Drupal
917-446-1555

**Comment by kellybell** [comment]
that's why i said integration.

Kelly Bell
Founder and CTO
Gotham City Drupal
917-446-1555

**Comment by andrewmallis** [comment]
Connecting Tower to a remote upstream is an issue unrelated to Kalabox. 

Setting multiple upstreams can be done in the .git/config for the project and is a particular workflow decision. Tower can [assist you there](http://www.git-tower.com/files/applicationHelp/pgs/Refs_Remotes_Add.html).

Personally, I can understand a need for 2 remote upstreams, like Pantheon and github you would need to push to, but having one of your "remotes" be local is much, much less useful than using branches when working with Pantheon, if not totally cumbersome.

**Comment by kellybell** [comment]
Thanks Mallis! In had no idea - great to know
-K

Kelly Bell
Founder and CTO
Gotham City Drupal
917-446-1555

**Comment by pirog** [comment]
@kellybell i'm going to move this to V2 and milestone for alpha1 release.

**Comment by pirog** [comment]
https://github.com/kalabox/kalabox/issues/17
