### ISSUE TITLE
[FEAT REQ] UX: shows "Box Me" on startup, even after install

### ISSUE THREAD

**Issue by kellybell** [kalamuna/kalaboxv1#41]
I know this isn't actually a bug, but it IS a UX issue I think - more because it's there long enough for some user to hit Box Me again, and it's misleading and LOOKS like an error if users see it and they know they're supposed to be already installed. 

SO just a nice-to-have: put up a progress bar or something INSTEAD of this, once the Box has already been installed.

**Comment by pirog** [comment]
Agreed... Sadly it's actually more complicated than it looks... A vestige
of the appjs to node-WebKit migration.

On Tuesday, July 1, 2014, Kelly Bell notifications@github.com wrote:

> I know this isn't actually a bug, but it IS a UX issue I think - more
> because it's there long enough for some user to hit Box Me again, and it's
> misleading and LOOKS like an error if users see it and they know they're
> supposed to be already installed.
> 
> SO just a nice-to-have: put up a progress bar or something INSTEAD of
> this, once the Box has already been installed.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kalamuna/kalabox/issues/41.

## 

Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by kellybell** [comment]
oh well. on to v2!!!

Kelly Bell
Founder and CTO
Gotham City Drupal
917-446-1555

**Comment by pirog** [comment]
yeah totally! i dont think we will be adding many features, if any, to V1 if we get the $$ to work on V2.

**Comment by pirog** [comment]
@kellybell im going to move and milestone this for V2
