### ISSUE TITLE
Unexpected error while installing

### ISSUE THREAD

**Issue by possiBri** [kalamuna/kalaboxv1#43]
As per the instructions, here is the log info. Also, I just now noticed that it says it was installing beta6 but the file I d/l said beta7. Maybe it's just a typo, but I figured I should mention it!
### Kalabox Log

2014-07-03T22:19:56.127Z - info: Box initialized.
2014-07-03T22:19:56.128Z - info: Kalabox Version: 1.0-beta6
2014-07-03T22:19:56.128Z - info: Mac OS Version: 10.9.4

2014-07-03T22:19:56.129Z - info: VirtualBox Version: false
2014-07-03T22:19:56.129Z - info: Vagrant Version: false
2014-07-03T22:20:24.749Z - info: VirtualBox not installed or wrong version. Installing.
2014-07-03T22:20:24.750Z - info: User granted permission to install VirtualBox
2014-07-03T22:20:48.644Z - info: Successfully downloaded VirtualBox DMG.
2014-07-03T22:20:59.830Z - info: Successfully mounted VirtualBox DMG.
2014-07-03T22:21:00.420Z - info: VirtualBox installation complete.
2014-07-03T22:21:00.511Z - info: Successfully ejected VirtualBox DMG.
2014-07-03T22:21:00.513Z - info: Vagrant not installed or wrong version. Installing.
2014-07-03T22:21:00.513Z - info: User granted permission to install Vagrant
2014-07-03T22:21:06.106Z - info: Successfully downloaded Vagrant DMG.
2014-07-03T22:21:10.090Z - info: Successfully mounted Vagrant DMG.
2014-07-03T22:21:10.672Z - info: Vagrant installation complete.
2014-07-03T22:21:10.753Z - info: Successfully ejected Vagrant DMG.
2014-07-03T22:22:00.118Z - info: Box image downloaded.
2014-07-03T22:22:00.285Z - info: Installing Vagrant plugin vagrant-hostsupdater
2014-07-03T22:22:00.297Z - error: Error during installation routine: An error occurred in an async call.
cause stack is ...
  Error: Command failed: /bin/sh: vagrant: command not found

**Comment by possiBri** [comment]
Forgot to mention that this is on a brand new MBP that hasn't had previous versions of Kalabox installed or really much of anything besides Chrome and other standard apps.

**Comment by pirog** [comment]
Yeah that is my bad on the version :) if the dmg says beta 7 trust that!

If you open up a terminal can you run "vagrant --version" and print the output?

**Comment by pirog** [comment]
also great username :)

**Comment by possiBri** [comment]
haha thanks! And now, looking at the requirements I see I need to install vagrant and virtualbox, which I completely missed >_<. I'm guessing this is what caused the error, so I'm going to install those, try again, and get back to you asap. Thanks for the quick reply!

**Comment by pirog** [comment]
Kalabox should actually install those things for you and according to the log it did... so it is puzzling why it doesnt think the vagrant command exists. 

Were you prompted for your admin password when you started the installer?

**Comment by possiBri** [comment]
I sure was, and when I ran vagrant --version  I did receive the message "vagrant: command not found" so I assumed that was my fault for not installing.

Now that I'm thinking about it though, I've got a separate admin account, so perhaps I need to actually install logged in as admin, and not just put in admin pw. Will try that now.

**Comment by pirog** [comment]
yeah  you def need to install as an admin user because Kalabox will install a bunch of stuff on your system!

**Comment by possiBri** [comment]
Definitely! I'm so used to invoking admin from my "regular" account that I didn't even think about it. So I  logged into the admin account and clicked Box Me! but now it seems to be hung on the initial "downloading stuff" screen. Since I started the install before, is there something I need to clean/remove to start fresh?

**Comment by pirog** [comment]
in the DMG there is an Uninstall.tool you can run. Option #2 is a complete uninstall but i _think_ you should be fine without running that.

**Comment by possiBri** [comment]
Still hung after running Uninstall.too and using option 2.

**Comment by pirog** [comment]
:(
i haven't tried this on OSX 10.9.4 yet. I wonder if that breaks something in node-webkit. Let me roll a more recent release for you with that new stuff and you can try that out. Are you down?

**Comment by possiBri** [comment]
I am super down! You're awesome, thanks =]

**Comment by possiBri** [comment]
WAIT! I ran the unintall.tool again and this time it actually asked for pw. And now it's not hung. Will update ASAP!

**Comment by possiBri** [comment]
HA! I have been boxed and can now see the dashboard and everything. Thanks again for your help and awesome replacement for the dinosaur that is MAMP (I thoroughly enjoyed your presentation at Drupalcon)!

**Comment by pirog** [comment]
Awesome! Maybe the password dialog box got hidden the first couple tries?

On Thursday, July 3, 2014, possiBri notifications@github.com wrote:

> WAIT! I ran the unintall.tool again and this time it actually asked for
> pw. And now it's not hung. Will update ASAP!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kalamuna/kalabox/issues/43#issuecomment-47994614.

## 

Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by possiBri** [comment]
Well, it was the pw prompt within the Uninstall.tool... I hadn't been asked for one when running it the first time, but when I ran it a second time it asked... so not sure what happened, but once I gave the pw I'm guessing it actually removed stuff instead of just saying it was removed.

**Comment by pirog** [comment]
Oh you were there? Thanks! V2 is going to make V1 look a dinosaur too.
Which means MAMP will be going out of style like the Permian extinction.

Let me know if you have any other issues!

On Thursday, July 3, 2014, possiBri notifications@github.com wrote:

> HA! I have been boxed and can now see the dashboard and everything. Thanks
> again for your help and awesome replacement for the dinosaur that is MAMP
> (I thoroughly enjoyed your presentation at Drupalcon)!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kalamuna/kalabox/issues/43#issuecomment-47995054.

## 

Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by possiBri** [comment]
Yeah, and was just waiting for my new MBP to install... this is a great start to a long weekend. Hope you also have a great one =]

**Comment by pirog** [comment]
I will! Going to close this but feel free to reopen or submit a new one if you have other issues!
