### ISSUE TITLE
Unable to install on "regular" account (using admin pw)

### ISSUE THREAD

**Issue by possiBri** [kalamuna/kalaboxv1#46]
Ok, so I've been able to install Kalabox on my admin account, but I can't access it on my non-admin account (my "main" account), even with running Kalabox from the command-line using my admin account and sudo (it shows me the Box Me prompt upon opening, and when I put in my admin password I get the error: A keychain cannot be found to store "root.").

If I try running Kalabox on my non-admin account normally, it doesn't prompt me for a password at all, and errors when it gets to the installation part of the process (as per issue #43).

Is there a way to make Kalabox available to my non-admin account once I've gotten it installed? I am not supposed to be using the admin account for daily use, so it's pretty important that I have this ability. Help!!

**Comment by possiBri** [comment]
Scratch that, I just saw the feature request regarding the Box Me still showing up, and actually let the dashboard load instead of immediately clicking Box Me (thinking I needed to). Sorry about that!

**Comment by pirog** [comment]
Going to reopen this issue. I think we can get this to work differently just be letting the user specify the full creds of an admin user ie the username and password. Right now we are assuming the current user is also an admin user which might not always be true. Let's see if we can get this to work so a normal user can install and KBOX with a admin accounts creds. 

Either way V2 should def work this way.

**Comment by pirog** [comment]
We are probably going to want to write a node module that wraps around oascript/vbscript/zenity (or better things) to provide GUI password prompting. 

Optionally we will want this input to be stored using the respective keychain programs for each OS.

**Comment by pirog** [comment]
https://github.com/kalabox/kalabox/issues/18
