### ISSUE TITLE
Try Kalabox on Linux/Write Instructions

### ISSUE THREAD

**Issue by reynoldsalec** [kalamuna/kalaboxv1#5]
If dependencies were manually installed in the correct locations, I'm guessing that the Kalabox UI would work on most Linux platforms. Would be great to get instructions written for that (and would be even MORE great to get someone to tweak the installer for Linux).

**Comment by rlnorthcutt** [comment]
Plus one on this... I've been watching the Kalabox project for awhile, but I use Linux (not MacOS). Surely there is a way to run it on Linux?

**Comment by andrewmallis** [comment]
The [kalastack](https://github.com/kalamuna/kalastack) runs great.
Some tips: https://github.com/kalamuna/kalastack/wiki/Tips-for-Installing-on-Ubuntu-Linux

The front-end control panel's in node and should run on Linux, but there are some bits dependencies that'd be required, and some other finessing that the [kickstarter](https://www.kickstarter.com/projects/kalabox/kalabox-advanced-web-tools-for-the-people) will help us universalize for other *nix than our unix.

**Comment by pirog** [comment]
I think this has been made more explicit in the KS campaign but the way we are building it there should be a debian package available that will be very similar to the MacOSX version.

**Comment by Nitty-Gritty** [comment]
Can you please note that only Macs are currently supported on this page: http://www.kalamuna.com/products/kalabox-1.0 as it's marketed on drupal.org and in video as easy for beginners yet has that large caveat beginners won't necessarily realise until they try to setup the .dmg file.

**Comment by reynoldsalec** [comment]
@Nitty-Grity updated on that page; also moved the requirements section on the wiki page to the top, so that should be über clear now.

**Comment by pirog** [comment]
There are a couple Mac explicit calls in the app but im going to roll a debian version and see what this BAMF does

**Comment by pirog** [comment]
I think this is about to become a bigger issue or its own milestone but its useful and needed for V2 so ...

**Comment by reynoldsalec** [comment]
You are my hero @pirog, shit is about to get real.

**Comment by pirog** [comment]
Prelim list of things we will need to change:
1. Linux based password popup and password storage
2. Installer needs to be able to install debian packages 
3. Linux node binary (still need a better overall approach here)
4. Use correct tmp dir. 
5. Firewall checking
6. Restarting virtualbox during install11
7. Checking mac version
8. Storing pantheon credentials
9. is curl installed on ubuntu by default?
10. opening folders and urls from the

**Comment by pirog** [comment]
Did some more research on this and i think it _might_ just be stupid for V2. Is their any considerable advantage to us running docker inside a VM on linux? I'm def thinking no. In that case we shouldn't support this on V1 since there is not a ton of benefit that we can port forward to v2. 

@labboy0276 ... can you try setting up https://github.com/kalamuna/kalastack-docker on Ubuntu and see how it goes and write some brief notes on it in the comments here?

**Comment by pirog** [comment]
@labboy0276 you shouldn't need to install boot2docker at all for this... just install the latest docker for debian linux and then try the other commands out. see if you can get things running. when it comes time to building a site you might want to ping @fluxsauce on the steps to get a site up using switchboard but i think he wrote pretty clear docs on the switchboard repo.

**Comment by fluxsauce** [comment]
@labboy0276 Yeah, mosdef let me know if you need a hand. https://github.com/fluxsauce/switchboard/blob/master/README.md should get you on a path to awesome.

**Comment by labboy0276** [comment]
I will win this

**Comment by labboy0276** [comment]
@fluxsauce @pirog 

OK so this is what John did:

Docker Install
sudo apt-get update
sudo apt-get install linux-image-generic-lts-raring linux-headers-generic-lts-raring
sudo reboot
sudo spt-get install apt-transport-https
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 36A1D7869245C8950F966E92D8576A8BA88D21E9
sudo sh -c "echo deb https://get.docker.io/ubuntu docker main /etc/apt/sources.list.d/docker.list"
sudo apt-get update
sudo apt-get install lxc-docker
sudo docker run -i -t ubuntu /bin/bash
exit

Kalastack-Docker:
cd ~
git clone https://github.com/kalamuna/kalastack-docker.git
cd kalastack-docker

docker run -d -v /var/run/docker.sock:/tmp/docker.sock -t pirog/kalabox-proxy
sudo docker run --name=test_data pirog/kaladata-docker
sudo docker run -d -t \
  -e VIRTUAL_HOST=test.kala \
    -e VIRTUAL_PORT=80 -p :22 -p :80 -p :3306 \
 --volumes-from="test_data" \
 --name="test.kala" \
 --hostname="test.kala" \
 pirog/kalastack-docker:12.04

Once built:
sudo docker ps
docker inspect 7a7fd3747fc4 | grep IPAddress (or whatever your docker number is)
sudo nano /etc/hosts
172.17.0.22 test.kala (or whatever your IP was)
ssh root@test.kala (pw: kala)

**Comment by labboy0276** [comment]
@pirog Everything within the docker container runs UBER slow and I cant get it to connect index.php.

SO, i went back in and added the ports and it worked all happily.  PROBLEM was that I was not setting the IP right and we figured that out with inspect.  I updated my instructions above

**Comment by pirog** [comment]
Makes sense. The containers should be super fast when configured correctly.

On Friday, July 4, 2014, John Ouellet notifications@github.com wrote:

> @pirog https://github.com/pirog Everything within the docker container
> runs UBER slow and I cant get it to connect index.php.
> 
> SO, i went back in and added the ports and it worked all happily. PROBLEM
> was that I was not setting the IP right and we figured that out with
> inspect. I updated my instructions above
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kalamuna/kalabox/issues/5#issuecomment-48052881.

## 

Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by labboy0276** [comment]
@pirog All seems well, but composser and drush commands take forever, drush is uber slow, any ideas? like this command drush sw-auth-login pantheon user@example.com password took 4 minutes to execute

**Comment by labboy0276** [comment]
I tried amny things, but to no avail, maybe it is a port thing, I am not sure.

All drush commands take significant time to run with this current setup I did

**Comment by pirog** [comment]
Are you passing in --debug and --verbose on your commands? Where is it
getting slowed down?

On Friday, July 4, 2014, John Ouellet notifications@github.com wrote:

> I tried amny things, but to no avail, maybe it is a port thing, I am not
> sure.
> 
> All drush commands take significant time to run with this current setup I
> did
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kalamuna/kalabox/issues/5#issuecomment-48070248.

## 

Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by labboy0276** [comment]
Yes it something that is happening prior to drush executing

**Comment by labboy0276** [comment]
I am pretty sure this has to do with php-cli and 5.4 weirdness and delays and things like that.  I have read many things, tried many things.  I even built my own docker container:

https://registry.hub.docker.com/u/labboy0276/kalastack-docker-5.3/

Git REPO

https://github.com/labboy0276/kalastack-docker-5.3

I am stuck with this, I have tried all John could.  @pirog @fluxsauce

**Comment by reynoldsalec** [comment]
Dropping the 1.x; it's not worth the effort to make the legacy Kalabox compatible with Linux.
