### ISSUE TITLE
Design new user interface for V2

### ISSUE THREAD

**Issue by pirog** [kalamuna/kalaboxv1#51]
We should have a new user interface and updated iconography/grfx for V2. Some high level goals that should be part of the design
1. No more "status" or "dash". The focus should be on sites.
2. We need to have "advanced" options hidden by default. This will ensure the UI remains clean and easy to use. 
3. We need better UX around listing sites and running site operations. 

@madeofpeople let's talk on the slacks about timeline for working on this. assuming you are interested of course :)

**Comment by thiagodemellobueno** [comment]
> No more "status" or "dash". The focus should be on sites.
> We need to have "advanced" options hidden by default. This will ensure the UI remains clean and easy to use.
> We need better UX around listing sites and running site operations.
> I like! and have some ideas!

Superinterested and happy to be tapped, lets talk tomorrow on it.

**Comment by pirog** [comment]
Perfect!

**Comment by pirog** [comment]
@madeofpeople so to get this party started lets ruminate and then maybe you can throw up some lo-fi sketches for discussion. 

I'm going to work on some other issues/wikis that help define the project better so those can help provide guidance as well!

**Comment by thiagodemellobueno** [comment]
@pirog here's a high level flow of adding a site, and deploying a site... so we can identify screens, and deeper flows. Asterisks imply where bubbles represent further flows that we may want to elaborate on.

![add-site-deployment-flow](https://cloud.githubusercontent.com/assets/79221/3617826/ff3a473a-0de2-11e4-9118-2173fbafb6ee.jpg)

**Comment by pirog** [comment]
This is great! Let me gather feedback and then i'll be back!

**Comment by pirog** [comment]
Ok i think this def has all the logic we need for a good V2 first build. The thing that i am most interested in at this point is how we can express these flows in the the fewest user actions as possible. 

For example, and maybe this is just me not understanding how this flowchart translates to a design, i dont know if we need to explicitly ask the user if they want to create a new site or pull a site from somewhere... maybe you just click "+" and the screen contains a sexy and well organized list of sites that are available. 

So on the same display something like "start a new project from" -> List of distros, wordpress, laravel, blank php project, etc and then tab/section/whatever with "or grab an existing project" and then it just lists all the sites you have at all your targets. I dont _think_ we need to explicitly say "here are your list of acquia sites", but we should have something like "don't see your project? click to integrate with your hosting provider" -> goes to settings page. 

I think maybe we can do something like this when it comes to pushing code/deploying back up. I don't want there to really be a difference between pushing code and deploying a site on the UX side... to the user it should all be about push/pull only. So we will basically only ever want the user to need to do those two actions... plus maybe entering their config. 

Is that kind of what you are thinking anyway?

**Comment by thiagodemellobueno** [comment]
This translates to design in the following ways.
1. It offloads whats in your head
2. It provides a reference point to collaborators talking about the same thing, but not their mental models.
3. It identifies easily overlooked, but non-edge-casey nooks and crannies.

The next step is to start defining each flow on a per-screen / per-field level  while achieving the purpose of the action.  For example you dont want there to be a difference from pushing / deploying... there still needs to be a way to 'deploy somewhere else' or 'change the deployment target before pushing.' 

The example you provide is a good example of why this excercize is necessary:
a. It serves two distinct use cases. 
b. In my mind we arent going to get away with offering a full list of distros without first branching off the platforms (correct me if im wrong but this could become a rather long list over time).... speaking of which defining the 'minmum supported options to ship with' would be very helpful and allow us to cater the interface for the task.

But as you see what you've done in paragraphs two and three of your response, is spell out a specific flow. The graphic is just there to get it out of your head, and put it somewhere where all the parties involved will be able to access it and talk about the same thing in a way thats more accesible/easy to visualize than the written word..

Or you'd have to write two to three paragraphs for every user interaction in the system (which is harder to read than a codified graphic with symbols and arrows).

**Comment by thiagodemellobueno** [comment]
@pirog here's some screens illustrating my thinking.
Perhaps a discussion soon? I'd also like to talk through the global settings (anything other than configuring targets go in there?)

Also I've been referring to 'deployment targets' as 'push target' but maybe we just call them targets?

My Sites as a list (access to most functionality from list) 
![mysites list](https://cloud.githubusercontent.com/assets/79221/3706039/7bc2a6f6-1425-11e4-961e-763a7f57e6ce.jpg) 
Methods may just show up on item hover (im into that stuff).

My Sites as cards, push/pull/config available.
![mysites cards](https://cloud.githubusercontent.com/assets/79221/3706041/7f1bd994-1425-11e4-924a-eadfa54da1f0.jpg)

Filter slides out on hover/touch (less clutter)
![mysites cards filter hovertouch](https://cloud.githubusercontent.com/assets/79221/3706042/83ccff22-1425-11e4-82a1-a1d1034f132a.jpg)

Options modal
![site options update modal tab](https://cloud.githubusercontent.com/assets/79221/3706379/ce4b4524-1428-11e4-9c91-e2cdcc5f1383.jpg)

Add Site
![site add modal](https://cloud.githubusercontent.com/assets/79221/3706382/d22a363c-1428-11e4-871e-6b9190b3be83.jpg)

Manage Push Targets
![settings manage pushtargets](https://cloud.githubusercontent.com/assets/79221/3706541/8f1cba70-142a-11e4-8a51-1b8b1228cb0f.jpg)
(^ should add a 'manage targets' button that takes you to the general screen, as well as a 'configure target' on each item)

Edit / Add Target
![target config](https://cloud.githubusercontent.com/assets/79221/3706463/c5f3d35e-1429-11e4-857f-354ae51e6af1.jpg)

**Comment by pirog** [comment]
@madeofpeople i think these are all great and lets def chat soon.

**Comment by pirog** [comment]
@madeofpeople this is annoying so im sorry but we moved the issue over here:
https://github.com/kalabox/kalabox/issues/19
