### ISSUE TITLE
Determine V2 start state... V1 or something else?

### ISSUE THREAD

**Issue by pirog** [kalamuna/kalaboxv1#54]
We need to figure out whether to use V1 as our starting point for V2 or start with something else like  https://github.com/Anonyfox/node-webkit-hipster-seed and then forward port relevant node modules from V1 to V2.

**Comment by mikemilano** [comment]
Any considerations for AngularJS? Not a client/server architecture, but actually accessing node libraries directly in Angular. I haven't done much with node-webkit, but I setup simple repo to test it out with angularjs here: https://github.com/mikemilano/nw-ng

**Comment by pirog** [comment]
I think Angular would be awesome. I'm sure @reynoldsalec would approve as well. I was looking at the https://github.com/Anonyfox/node-webkit-hipster-seed kit which seems intriguing but also maybe excessive? Not really sure how i feel 100% about it yet but something like that would be good. 

One of my big Q's right now is where to go from V1. What i mean by that is... i don't think it would be super hard to prototype V2 versions for Win/Deb by just hacking up V1. It would be great to show people things quickly. This is contrasted by my math brain desire to say F V1 lets start from scratch on something way better and just go more ground up. Maybe there is a way to do both, maybe we need to pick one. 

I'm leaning towards just starting from scratch but am not 100% sold on that. Do you have any thoughts here?

**Comment by mikemilano** [comment]
@pirog I like the idea of starting from scratch. AngularJS architecture is so different from anything else that there would be much re-writing anyway.

How do you feel about coffee script? I haven't drank that coolaide yet and not sure about the hipster seed. I just went with a simple but organized approach with the `nw-ng` example.

We could keep the V1 stuff in there for reference and run the v1 and v2 stuff on different index files until we're further along.

**Comment by pirog** [comment]
Perfect! I think that is what i am heavily leaning towards esp having just worked on the V1 code and realizing it's... well... it could be better :)

I like the idea of coffeescript but haven't really used it yet. I know @bassettsj is a big fan. I'm agnostic on it for use on V2 for now and looking at it more `nw-ng` or something like https://github.com/jgrenon/angular-desktop-app might be a better starting point than hipster seed. 

what do you think? i'd like to pick something soonish so we can actually open up a branch and some code for v2!

**Comment by mikemilano** [comment]
Based on a preliminary look at the `angular-desktop-app` it looks pretty decent. Is the idea to use it as a seed (just a starting point) or are you thinking of keeping in sync with it as they suggest?

I'm not sure how I feel about that. I think of a seed as something you base a project on, not sync up with.

I spun up the base project but it looks like it will take some time to give it a good workout.

Regarding coffeescript, I don't see the benefits personally. You are gaining "prettier"(?) short-hand of writing code, but your project gains dependencies and developers who may  not be familiar yet (such as you and I) will need to learn it before they understand and work on it. It may discourage potential contributors considering users of Kalabox are most likely not using coffeescript in any of their apps. I don't see the problem with JavaScript to warrant the additional dependencies. We're in the realm of opinion here though. :)

**Comment by pirog** [comment]
+1 on seeding. I dont really want to keep in sync unless there is something big i am missing there.

im going to try it out too so we can compare and contrast. i want to set next tuesday as our deadline to figure this out if possible. 

i am pretty sure i agree with you on coffeescript but as a big proponent i would love to hear @bassettsj make a case and address the concerns you've laid out re: dev collab.

**Comment by mikemilano** [comment]
There's a lot of opinion & complexity in this seed that I'm wondering is necessary.

I'm having a hard time wrapping my head around the need for jade for partials when Angular is responsible for the dom dynamics. There's other decisions I'm not fond of, like reserving `/src/lib` for vendor components and I'd probably approach the use of using an alternate router based on when it was actually necessary.

This seed would certainly command architecture decisions and I'm not sure what we would get out of it would make it better than making some of these decisions on our own.

I'm not a seasoned node/angular dev though, so it would be interesting to hear from others. If I didn't have more info than I have now though, I'd go with seeding from scratch.

**Comment by bassettsj** [comment]
There are a lot of reasons to use cofffeescript and it is a minor dependency. But whatever you want to do. I can write both.  -Steven

**Comment by pirog** [comment]
Good to know. I want to do whatever encourages the most outside development. 

@mikemilano maybe we just come fill circle here and rock your https://github.com/mikemilano/nw-ng ? What would be the major disadvantages of this?

**Comment by pirog** [comment]
now over here:
https://github.com/kalabox/kalabox/issues/15
