### ISSUE TITLE
Use sinker for file "sharing" instead of NFS.

### ISSUE THREAD

**Issue by reynoldsalec** [kalamuna/kalaboxv1#6]
If we're ok upgrading Kalastack to use rsync (see https://github.com/kalamuna/kalastack/issues/84), we should do a couple things to keep files synced between the environments:
1. Require Vagrant 1.5+
2. Use the "vagrant auto-sync" command on initializing the box to keep things automatically synced: https://www.vagrantup.com/blog/feature-preview-vagrant-1-5-rsync.html

That cool with you @pirog? This should solve the NFS issues we're having on Mavericks AND make the Box quite a bit faster.

**Comment by pirog** [comment]
Yeah definitely. There may be some other weird things that happen when we move past the 1.5 threshold so we will want to be mindful of that.

**Comment by kellybell** [comment]
++

NFS sucks a$$

**Comment by pirog** [comment]
@reynoldsalec would love to make this a focus for beta8

**Comment by reynoldsalec** [comment]
Definitely, maybe roundhouse with @substack next Friday if the good Mr. Halliday is free?

**Comment by pirog** [comment]
@reynoldsalec i'm going to move this over to V2 but it would still be valuable for V1 i think.
