### ISSUE TITLE
Spin up Laravel Sites

### ISSUE THREAD

**Issue by reynoldsalec** [kalamuna/kalaboxv1#66]
The Rails of PHP. Could be a good move for Kalabox to be in with the "it" crowd.

Composer would be necessary (assuming that's in 2.x?).

Laravel has a virtual environment: http://laravel.com/docs/homestead, but I think Kalabox could be a much friendlier way of allowing people to startup with Laravel.

**Comment by pirog** [comment]
anything that can make up for our sins of working with drupal is a +1 for me. @reynoldsalec
