### ISSUE TITLE
Virtualbox 4.3.12?

### ISSUE THREAD

**Issue by teampoop** [kalamuna/kalaboxv1#68]
I seem to be hanging out at the boot this box splash screen with no progress bar, or messaging or offers of a group hug. I checked the ~/.kalabox/kalabox.log and found this:

`2014-07-13T16:28:58.842Z - info: Kalabox Version: 1.0-beta6
2014-07-13T16:28:58.842Z - info: Mac OS Version: 10.9.3

2014-07-13T16:28:58.842Z - info: VirtualBox Version: 4.3.12r93733

2014-07-13T16:28:58.842Z - info: Vagrant Version: Vagrant 1.6.3

2014-07-13T16:29:05.318Z - info: Existing VirtualBox installation, version 4.3.12
2014-07-13T16:29:05.319Z - info: Existing Vagrant installation, version 1.6.3
2014-07-13T16:29:05.320Z - info: VirtualBox not installed or wrong version. Installing.`

Shouldn't I be cool with VirtualBox 4.3?

Thanks in advance.

**Comment by pirog** [comment]
Are you getting a password prompt when you try to install?

Currently V1 does not support vagrant 1.5+ so this could explain the failure here as well. If you want to try kalabox v1 and can sacrifice not having the most recent vagrant we recommend running the uninstall.tool packaged with the DMG and choosing option #2. THIS WILL UNINSTALL EVERYTHING SO BE CAREFUL!

**Comment by mark-casias** [comment]
Is there an issue open to support later versions of vagrant? I work with a lot of client boxes and feel using an older version would bork them.

**Comment by pirog** [comment]
Yes there is. I'm not sure how much movement there will be on it. It would be great to get it upgraded to work up to 1.6.3 but all efforts are on V2 which will bypass vagrant and thus not even have any of these issues :)

Here is the issue for ref:
https://github.com/kalamuna/kalabox/issues/28

**Comment by pirog** [comment]
@teampoop i think this issue is now resolved with https://github.com/kalamuna/kalabox/issues/74 should be in the next release
