### ISSUE TITLE
Git Connection problems

### ISSUE THREAD

**Issue by dsbrianwebster** [kalamuna/kalaboxv1#69]
Pretty sure this started happening after beta7 --
When we try to git pull or push for example we keep getting...

Permission denied (password,publickey).
fatal: The remote end hung up unexpectedly

![screen shot 2014-07-13 at 10 59 40 pm](https://cloud.githubusercontent.com/assets/8154653/3567492/0f766a30-0b1c-11e4-8e05-35720c726dbc.png)

This issue reports a "similar" problem, but pertaining to communicating with Pantheon
https://github.com/kalamuna/kalabox/issues/12

Kalabox is retrieving pantheon sites just fine for me, but when we ssh into the box and run git commands all we get is the aforementioned error.

Tried uninstalling then reinstalling kalabox, same issue.

Installed it on a brand new mac, same issue.

One odd thing is that the DMG I ran definitely was beta7, when I check the log I see...

**2014-07-14T05:17:39.248Z - info: Kalabox Version: 1.0-beta6**
2014-07-14T05:17:39.248Z - info: Mac OS Version: 10.9.4
2014-07-14T05:17:39.248Z - info: VirtualBox Version: 4.3.6r91406
2014-07-14T05:17:39.248Z - info: Vagrant Version: Vagrant 1.4.3
2014-07-14T05:17:39.248Z - info: Installation completed successfully. 

Lastly, every time I ssh into the box I get the following warning which I never had before...

![screen shot 2014-07-13 at 11 02 50 pm](https://cloud.githubusercontent.com/assets/8154653/3567515/f1d80d8e-0b1c-11e4-83e7-404f71b931ac.png)

Thanks in advance for all help and thanks for Kalabox!

**Comment by reynoldsalec** [comment]
Hmm, don't know about the error when ssh-ing in, but if you run "ssh-add ~/.ssh/terminatur.id_rsa" you should be able to use all your git commands as normal.

**Comment by dsbrianwebster** [comment]
![screen shot 2014-07-14 at 9 57 46 am](https://cloud.githubusercontent.com/assets/8154653/3573949/fe275eea-0b77-11e4-84cc-749bfbce5131.png)

**Comment by reynoldsalec** [comment]
@dsbrianwebster try running this:

eval "$(ssh-agent)"

**Comment by dsbrianwebster** [comment]
ran it from the box...
   Agent pid 15412

**Comment by pirog** [comment]
can you git pull after running eval "$(ssh-agent)"? 

re: the ssh warning, we switched the logic here to use the normal mac "open ssh://" handler so this is actually expected behavior. This will now launch your default ssh handler instead of just Terminal so iTerm2 users can now benefit as well.

**Comment by dsbrianwebster** [comment]
Thanks for the help. Good to know re the ssh warning.

still getting the same error...
Permission denied (password,publickey).
fatal: The remote end hung up unexpectedly

after trying to pull after  eval "$(ssh-agent)"?

**Comment by pirog** [comment]
I would try clearing out the drush cache when after you ssh in with "rm -rf
~/.drush/cache" and then restarting kalabox.

On Mon, Jul 14, 2014 at 4:06 PM, dsbrianwebster notifications@github.com
wrote:

> Thanks for the help. Good to know re the ssh warning.
> 
> still getting the same error...
> 
> Permission denied (password,publickey).
> fatal: The remote end hung up unexpectedly
> 
> after trying to pull after eval "$(ssh-agent)"?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kalamuna/kalabox/issues/69#issuecomment-48971643.

## 

Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by dsbrianwebster** [comment]
Cleared drush cache via --
rm -rf ~/.drush/cache

Restarted box

Same error on git pull

running eval "$(ssh-agent)" returned different results this time (below)...

![screen shot 2014-07-14 at 5 23 05 pm](https://cloud.githubusercontent.com/assets/8154653/3579063/419d296e-0bb6-11e4-92f5-7d80d9c18631.png)

**Comment by pirog** [comment]
Does this happen on all your sites or just sites you built pre-Beta7?

On Mon, Jul 14, 2014 at 5:25 PM, dsbrianwebster notifications@github.com
wrote:

> Cleared drush cache via --
> rm -rf ~/.drush/cache
> 
> Restarted box
> 
> Same error on git pull
> 
> running eval "$(ssh-agent)" returned different results this time (below)...
> 
> [image: screen shot 2014-07-14 at 5 23 05 pm]
> https://cloud.githubusercontent.com/assets/8154653/3579063/419d296e-0bb6-11e4-92f5-7d80d9c18631.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kalamuna/kalabox/issues/69#issuecomment-48976877.

## 

Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by dsbrianwebster** [comment]
I believe it was happening on all my sites before I did the wipe and started fresh. The only sites I have now are the ones I fetched from kalabox after Beta-7 and yes, I can't git push/pull in any of them.

**Comment by dsbrianwebster** [comment]
just downloaded another panth site to see if maybe any of the stuff we tried had an effect on a new site. Site still downloaded successfully, but I also still get the same git errors after I ssh in.

**Comment by dsbrianwebster** [comment]
Ran the uninstall tool, chose option 1, then installed --
https://github.com/kalamuna/kalabox/tree/1.0-beta6

ssh'd in, ran git pull and SUCCESS.

Def seems to be a prob w/Beta 7

Sorry I couldn't stay on Beta7 longer and keep testing, needed my workflow back.

I'll keep this open in case I can help further.

**Comment by pirog** [comment]
Very strange. Almost everyone is reporting the exact opposite ie beta6 problems beta7 successes. :/ Glad it worked for you to revert but should def try to figure out the issue. 

What is the most strange is that you pull your pantheon site via git as well so if it works there a normal git pull from CLI should also work. 

If you had a previous version maybe you were never prompted to download updates?

**Comment by steveoliver** [comment]
I received a similar message (from bitbucket) when I attempted `git push` from OSX for the first time since setting up Kalabox:

> **\* Authorization Error or Repository Not Found ***
> 
> Your key is not attached to the repository and account you are trying to access.
> Don't hesitate to contact support for assistance at ....
> 
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.

The solution for OSX, just as it is within kalabox, was to run `ssh-add ~/.ssh/id_rsa`.

**Comment by gremy** [comment]
I tried it on a fresh kalabox compiled version of the 1.x branch and I did not have this problem. I can easily pull any new updated from pantheon repositories.
I did however pushed a merge request to update the VERSION_STRING in kalabox,json to beta7.

**Comment by reynoldsalec** [comment]
Having looked at this and been in communication with @pirog, our preferred solution for this issue would be to: 

1) Create a drush command in Terminatur that performs terminatur_bootstrap (but does not load the site list) to correctly load the keys.
2) Run that at the end of box start.

**Comment by pirog** [comment]
this is actually going to be kind of a joke fix i think
`_terminatur_keys()` 
already does everything. 

just need to make it into a drush function or maybe we an just hit it as is with drush exec.

**Comment by pirog** [comment]
yeah 
`drush php-eval "_terminatur_keys();"` does the trick but now getting

Could not open a connection to your authentication agent ?

**Comment by pirog** [comment]
eval $(ssh-agent) first

**Comment by ModulesUnraveled** [comment]
I'm having trouble pushing and pulling with Git.

I just read through the post, and tried what I think should have been the solution, but it didn't work. Here's what I see in my terminal:

```
vagrant@kala:/var/www/new-mu-site$ git pull
Permission denied (password,publickey).
fatal: The remote end hung up unexpectedly
vagrant@kala:/var/www/new-mu-site$ ssh-add ~/.ssh/id_rsa
Could not open a connection to your authentication agent.
vagrant@kala:/var/www/new-mu-site$ eval $(ssh-agent)
Agent pid 3878
vagrant@kala:/var/www/new-mu-site$ ssh-add ~/.ssh/id_rsa
/home/vagrant/.ssh/id_rsa: No such file or directory
vagrant@kala:/var/www/new-mu-site$ git pull
Permission denied (password,publickey).
fatal: The remote end hung up unexpectedly
vagrant@kala:/var/www/new-mu-site$
```

Do I need to create keys from within Kalabox and add those to Pantheon through their dashboard?

**Comment by steveoliver** [comment]
@ModulesUnraveled it looks like you'll need to:
1. ssh-keygen
2. ssh-add
3. yes, add that key to pantheon (and wherever else it needs to be, like GitHub, etc.).

**Comment by allenfear** [comment]
I noticed that the keys generated through the Kalabox installation process were named:
terminatur.id_rsa
terminatur.id_rsa.pub
I renamed them to 'id_rsa' and 'id_rsa.pub' and that fixed the issue for me.

**Comment by pirog** [comment]
@reynoldsalec since we aren't doing key forwarding anymore maybe it would be ok to just name these keys the default names? especially if the user is in the kalabox environment in terminatur?

**Comment by allenfear** [comment]
I probably should have been more specific and said that I did this:

```
$ cp terminatur.id_rsa id_rsa
$ cp terminatur.id_rsa.pub id_rsa.pub
```

So I have both sets of keys, and running git against pantheon works both in my kalabox environment and through my host system at ~/kalabox/www/mysite

**Comment by pirog** [comment]
yes. makes complete sense. 
hopefully we can roll this into the upstream in terminatur so everyone gets the update. in the meantime, people who don't want to rename their keys can do something like this:

```
File ~/gitwrap.sh
```

```
#!/bin/bash
ssh -i ~/.ssh/terminatur.id_rsa $@
```

Then, in my `.bashrc`, add the following:

```
export GIT_SSH=~/gitwrap.sh
```
