### ISSUE TITLE
kalabox on linux

### ISSUE THREAD

**Issue by laurencefass** [kalamuna/kalaboxv1#70]
i just watched recent kalabox promotion vid says that kb is working on linux. i cant find any decent installation guides on the web... if anyone can link me to one would be much appreciated... debian environments preferred... thanks.

**Comment by pirog** [comment]
Hmmm i'm not sure that is true.. which video is this? That said think V1 COULD be adapted to work on Debian without a ton of struggle. See https://github.com/kalamuna/kalabox/issues/5 for more info. There is def no "supported" way to do this on V1 as of yet although https://github.com/kalamuna/kalastack gets you pretty far if you are CLI-friendly.

We are hoping for relatively parallel V2 releases for OSX/Windows/Debian so i'd track the milestones there!

**Comment by laurencefass** [comment]
thanks ill keep an eye on developments...

**Comment by pirog** [comment]
awesome! we are hoping to launch a linux prototype in the next month or so!
