### ISSUE TITLE
VirtualBox update?

### ISSUE THREAD

**Issue by ultimike** [kalamuna/kalaboxv1#71]
I was about to install Kalabox and I noticed that wants to download a newer version of VirtualBox than what I currently have on my system.

I currently use VirtualBox 4.1.20 to boot into Windows 7. I can't have this go sideways because I run our business using QuickBooks in the Windows 7 environment. 

If I update VirtualBox (or let Kalabox update it) will my existing virtual machines still work without any re-configuration?

Thanks,  
-mike

**Comment by reynoldsalec** [comment]
Hey @ultimike, my guess would be that everything should be fine, I haven't seen an upgrade to VirtualBox cause problems with any of my existing virtual environments. That said, I would highly recommend exporting your Windows 7 virtual environment so you have a backup in case you need to go back to the older VirtualBox environment and re-import it. Never hurts being careful.

**Comment by pirog** [comment]
@ultimike, pretty sure it is fine as well but you should 100% export your VB appliances first to be sure!

**Comment by pirog** [comment]
@ultimike feel free to reopen!
