### ISSUE TITLE
Improve admin password dialog

### ISSUE THREAD

**Issue by chrowe** [kalamuna/kalaboxv1#73]
Based on https://github.com/kalamuna/kalabox/wiki/Troubleshooting-Kalabox-Problems#what-i-had-to-enter-my-password I see that this is an issue for people.

When I read it, I thought it was asking me to create a new admin password for Kalabox.

It sounds like, in fact you want people to enter the password for the current mac user and assume that they are an admin.

If so, I suggest the text read something like

> Please enter your Mac user account password. Installation will fail if your account does not have administrative privileges.

Even better would be to use the default mac dialog for this.

**Comment by pirog** [comment]
Yes! Agreed with all of these things and we are definitely going to implement these improvements for V2. In the meantime if you want to submit a PR for the text change i'll gladly roll that in since we can do that easy!
