### ISSUE TITLE
complex drupal commerce site from Pantheon errors on most web requests

### ISSUE THREAD

**Issue by dsacks** [kalamuna/kalaboxv1#77]
I have a complex drupal commerce site on Pantheon that I brought down with Kalabox (!) however it almost always gives this error when you try to do anything with it (see below).

I just downloaded Kalabox and installed yesterday. My site on Pantheon is based on Panapoly and Drupal Commerce. I tried creating a new site in Kalabox and importing the backed-up database, code and files, but I get the same error. I wonder if it is resource based.

( ! ) Fatal error: Class name must be a valid object or a string in /var/www/localaopdev/includes/common.inc on line 7870
Call Stack
# Time    Memory  Function    Location

1   0.0011  646768  {main}( )   ../index.php:0
2   0.0031  749368  drupal_bootstrap( ) ../index.php:24
3   0.0355  3402272 _drupal_bootstrap_full( )   ../bootstrap.inc:2285
4   0.3022  10915752    menu_set_custom_theme( )    ../common.inc:5177
5   0.3022  10915832    menu_get_custom_theme( )    ../menu.inc:1770
6   0.3026  10924320    menu_get_item( )    ../menu.inc:1755
7   0.3027  10924832    menu_rebuild( ) ../menu.inc:459
8   0.3044  10956704    menu_router_build( )    ../menu.inc:2721
9   1.3442  38543816    call_user_func ( )  ../menu.inc:2752
10  1.3442  38543816    search_api_page_menu( ) ../menu.inc:0
11  1.3443  38555496    search_api_page_load_multiple( )    ../search_api_page.module:45
12  1.3443  38555720    entity_load( )  ../search_api_page.module:361
13  1.3443  38555720    entity_get_controller( )    ../common.inc:7834

**Comment by pirog** [comment]
Doesn't appear to be resource based. Generally this type of thing happens when you are trying to load an entity that doesn't actually exist anymore. I'm not sure if that helps narrow things down at all. 

Does your development site work correctly on pantheon?

**Comment by dsacks** [comment]
Yes, it does work correctly on Pantheon. I am refreshing it to see if that makes any difference.

**Comment by pirog** [comment]
_usually_ these kinds of errors can show up if you have corrupted data in your DB but if that's true it would mess up on pantheon also. You could always try importing your LIVE database directly into kalabox and see if that makes a difference. 

I assume you are doing all the normally cache clearing things on Kalabox? although im not sure that should matter for this.

**Comment by dsacks** [comment]
The error will come up, then I'll hit the browser 'reload' button and it will bring the site up correctly, then I'll click on a link and get the error, hit 'reload'...

When I tried to clear cache, I got this:

( ! ) Warning: include_once() [function.include-once]: Unable to allocate memory for pool. in /var/www/aop/includes/theme.inc on line 565
Call Stack

# Time    Memory  Function    Location

1   0.0007  650344  {main}( )   ../index.php:0
2   5.9045  12970488    menu_execute_active_handler( )  ../index.php:25
3   5.9056  12973936    call_user_func_array ( )    ../menu.inc:517
4   5.9056  12974304    admin_menu_flush_cache( )   ../menu.inc:0
5   5.9057  12975672    drupal_flush_all_caches( )  ../admin_menu.inc:898
6   11.9861 16841552    menu_rebuild( ) ../common.inc:7500
7   11.9869 16842848    menu_router_build( )    ../menu.inc:2721
8   12.7015 39705320    call_user_func ( )  ../menu.inc:2752
9   12.7015 39705320    search_api_page_menu( ) ../menu.inc:0
10  12.7015 39716904    search_api_page_load_multiple( )    ../search_api_page.module:45
11  12.7015 39717128    entity_load( )  ../search_api_page.module:361
12  12.7016 39721256    EntityAPIControllerExportable->load( )  ../common.inc:7834
13  12.7016 39721568    EntityAPIController->load( )    ../entity.controller.inc:730
14  12.7016 39722352    EntityAPIController->query( )   ../entity.controller.inc:249
15  12.7016 39722352    EntityAPIControllerExportable->buildQuery( )    ../entity.controller.inc:186
16  12.7016 39722664    EntityAPIController->buildQuery( )  ../entity.controller.inc:713
17  12.7016 39722664    DrupalDefaultEntityController->buildQuery( )    ../entity.controller.inc:170
18  12.7017 39732720    SelectQuery->fields( )  ../entity.inc:279
19  12.7017 39734320    _drupal_error_handler( )    ../bootstrap.inc:0
20  12.7017 39734320    _drupal_error_handler_real( )   ../bootstrap.inc:2338
21  12.7019 39759904    _drupal_log_error( )    ../errors.inc:75
22  12.7033 39762288    theme( )    ../errors.inc:245
23  12.7033 39762368    theme_get_registry( )   ../theme.inc:1020
24  12.7034 39763632    call_user_func_array ( )    ../theme.inc:277
25  12.7034 39764512    _theme_load_registry( ) ../theme.inc:0
26  12.7034 39766008    ThemeRegistry->__construct( )   ../theme.inc:335
27  12.7039 39766488    ThemeRegistry->initializeRegistry( )    ../theme.inc:395
28  12.7039 39766488    theme_get_registry( )   ../theme.inc:411
29  12.7039 39766728    call_user_func_array ( )    ../theme.inc:277
30  12.7039 39767480    _theme_load_registry( ) ../theme.inc:0
31  12.7044 39767640    _theme_build_registry( )    ../theme.inc:325
32  12.7057 39820648    _theme_process_registry( )  ../theme.inc:689

**Comment by pirog** [comment]
ok well that is DEF a mem issue. usually you can clear out those pool
errors by going into your box and just restarting php-fpm.

SSH in with the ssh button and run "sudo service php5-fpm restart" that
should clear the pool errors.

Do you have some basic metrics for the size of your site? like size of
code, data files?

On Thu, Jul 17, 2014 at 3:34 PM, dsacks notifications@github.com wrote:

> The error will come up, then I'll hit the browser 'reload' button and it
> will bring the site up correctly, then I'll click on a link and get the
> error, hit 'reload'...
> 
> When I tried to clear cache, I got this:
> 
> ( ! ) Warning: include_once() [function.include-once]: Unable to allocate
> memory for pool. in /var/www/aop/includes/theme.inc on line 565
> Call Stack
> Time Memory Function Location
> 
> 1 0.0007 650344 {main}( ) ../index.php:0
> 2 5.9045 12970488 menu_execute_active_handler( ) ../index.php:25
> 3 5.9056 12973936 call_user_func_array ( ) ../menu.inc:517
> 4 5.9056 12974304 admin_menu_flush_cache( ) ../menu.inc:0
> 5 5.9057 12975672 drupal_flush_all_caches( ) ../admin_menu.inc:898
> 6 11.9861 16841552 menu_rebuild( ) ../common.inc:7500
> 7 11.9869 16842848 menu_router_build( ) ../menu.inc:2721
> 8 12.7015 39705320 call_user_func ( ) ../menu.inc:2752
> 9 12.7015 39705320 search_api_page_menu( ) ../menu.inc:0
> 10 12.7015 39716904 search_api_page_load_multiple( )
> ../search_api_page.module:45
> 11 12.7015 39717128 entity_load( ) ../search_api_page.module:361
> 12 12.7016 39721256 EntityAPIControllerExportable->load( )
> ../common.inc:7834
> 13 12.7016 39721568 EntityAPIController->load( )
> ../entity.controller.inc:730
> 14 12.7016 39722352 EntityAPIController->query( )
> ../entity.controller.inc:249
> 15 12.7016 39722352 EntityAPIControllerExportable->buildQuery( )
> ../entity.controller.inc:186
> 16 12.7016 39722664 EntityAPIController->buildQuery( )
> ../entity.controller.inc:713
> 17 12.7016 39722664 DrupalDefaultEntityController->buildQuery( )
> ../entity.controller.inc:170
> 18 12.7017 39732720 SelectQuery->fields( ) ../entity.inc:279
> 19 12.7017 39734320 _drupal_error_handler( ) ../bootstrap.inc:0
> 20 12.7017 39734320 _drupal_error_handler_real( ) ../bootstrap.inc:2338
> 21 12.7019 39759904 _drupal_log_error( ) ../errors.inc:75
> 22 12.7033 39762288 theme( ) ../errors.inc:245
> 23 12.7033 39762368 theme_get_registry( ) ../theme.inc:1020
> 24 12.7034 39763632 call_user_func_array ( ) ../theme.inc:277
> 25 12.7034 39764512 _theme_load_registry( ) ../theme.inc:0
> 26 12.7034 39766008 ThemeRegistry->__construct( ) ../theme.inc:335
> 27 12.7039 39766488 ThemeRegistry->initializeRegistry( ) ../theme.inc:395
> 28 12.7039 39766488 theme_get_registry( ) ../theme.inc:411
> 29 12.7039 39766728 call_user_func_array ( ) ../theme.inc:277
> 30 12.7039 39767480 _theme_load_registry( ) ../theme.inc:0
> 31 12.7044 39767640 _theme_build_registry( ) ../theme.inc:325
> 32 12.7057 39820648 _theme_process_registry( ) ../theme.inc:689
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kalamuna/kalabox/issues/77#issuecomment-49375560.

## 

Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by dsacks** [comment]
code/files are 484 MB
database sql script is 105.1MB

**Comment by dsacks** [comment]
I tried pulling the database from live and putting it in Kalabox. Same problem with the Fatal error: Class name ...

**Comment by pirog** [comment]
Hmmm yeah that is a pretty modest size site for kalabox... 

@reynoldsalec do you have any potential insight here? It screams "code error" to me, ie not really a kalabox issue, but it works on pantheon so... ?

**Comment by reynoldsalec** [comment]
Yeah @pirog, I suspect you are correct that there is some code issue, it's possible that this might be due to some slight configuration difference between Pantheon and Kalabox. 

@dsacks, you could  try a couple of the things indicated on this post: https://www.drupal.org/node/1667536
- running update.php and clearing cache
- making sure you don't have any custom code in a PHP field in Views (or possibly elsewhere)

Do you use Redis or Solr on the Pantheon site? That could be the problem as well. It's pretty easy to install Redis and Solr on Kalabox, can give you instruction links if that's the case.

**Comment by dsacks** [comment]
I think we are using both Redis and Solr. For sure Solr.

**Comment by andrewmallis** [comment]
Sounds like a problem with the DB to me. I would also suggest manually exporting from Pantheon and importing manually.

I use Sequel Pro. Easy:
https://kalamuna.atlassian.net/wiki/display/KALA/connecting+to+remote+MySQL+servers

**Comment by reynoldsalec** [comment]
@dsacks to find out, try disabling the redis module and search_api.

The "Fatal error: Class name ..." error you posted originally that seems to be the thing sticking looks like a problem that happens in building the menu routing for search_api; this could either be because your site is looking for a cache_menu entry in redis that isn't there (since you don't have redis) or potentially missing something with Solr.

**Comment by pirog** [comment]
@dsacks any progress on this?

**Comment by dsacks** [comment]
I did a refresh with new backup of the site in Kalabox and it actually seems to work okay now. So all I can figure is it was content/development issues last week.

The only issue I've seen is an error when trying to clear all caches in Drupal:

Error: DatabaseSchemaObjectExistsException: Table <em class="placeholder">field_data_field_sort</em> already exists. in DatabaseSchema->createTable() (line 657 of /var/www/aop/includes/database/schema.inc).

But other functionality seems to be working okay.

Thanks Mike.

**Comment by 13rac1** [comment]
I suggest closing. This issue is detailed here and is out of scope for Kalabox: https://www.drupal.org/node/2264123

It's related to the caching system.

**Comment by pirog** [comment]
thanks @eosrei. agreed and done.
