### ISSUE TITLE
Too many sites causes Kalabox auth to fail?

### ISSUE THREAD

**Issue by bwood** [kalamuna/kalaboxv1#8]
After installing Kalabox I tried to authenticate to Pantheon using by bwood@berkeley.edu account.  That account is part of the UC Berkeley "organization" on Pantheon.  I am positive I used the correct password because I first authenticated to http://dashboard.getpantheon.com by pasting my password and that succeeded.  Pasting the same password into the Kalabox password box results in "Unable to sign in. Please check your credentials."

I can successfully authenticate to Pantheon using a Pantheon account that is not part of a Pantheon organization.

Unfortunately this is a blocker for use of Kalabox at UC Berkeley.  We have about 100 people (and growing) using Pantheon, but they are all members of the UC Berkeley organization on Pantheon.

**Comment by andrewmallis** [comment]
I had this same problem today. Tried it again a few times and it logged in.
First time for me, though. Maybe on the Pantheon side?
Can you auth via terminus but not kalabox when this happens?

**Comment by bwood** [comment]
Andrew, are organization accounts _known_ to work with Kalabox?

> Can you auth via terminus but not kalabox when this happens?

Are you suggesting a workaround that would allow me to download some of my Pantheon sites to Kalabox?  This is what I'm trying to do...

**Comment by andrewmallis** [comment]
Our kalamuna.com email accounts are organizational also and they are known to work.

I was suggesting a quick check to see if the auth issues are on kalabox side of the equation for troubleshooting.

If you want to download sites, you can use [terminatur](https://github.com/kalamuna/terminatur) commands, which is what the UI triggers. Just SSH into the box and run:

```
$ drush pullsite mysite.dev
```

which should build the vhost and everything too.
Though you'd need your pantheon aliases file in place first, which is what authenticating does, so that might not work straight up. You can run 

   $  pantheon-aliases

I think to update the Pantheon Drush alias file at ~/.drush/pantheon.aliases.drushrc.php

However, I think if you try stopping and starting the box, then try a to authenticate again it should take.

**Comment by pirog** [comment]
@bwood another thing i would try is to login manually with terminus via the command line. You can do this by hitting the SSH button on the box.

$ drush pantheon-auth --debug --verbose

and copy the output here

**Comment by bwood** [comment]
Hi Mike,

So this problem is specific to my bwood@berkeley.edu account.  One of my coworkers can authenticate.  I just tried restarting Kalabox and authenticating using a pasted password that works with dashboard.getpatheon.com.  I even tried changing my Pantheon password to something containing just lower case letters.  I still can't get Kalabox to connect. 

In case it's relevant, I have a lot of Pantheon sites:

```
[bwood@mbp ~]$ drush psites |wc -l
     208
```

Here's the pauth output:

```
[bwood@mbp ~]$ drush pauth --debug --verbose
Bootstrap to phase 0. [0 sec, 2.18 MB]                               [bootstrap]
Drush bootstrap phase : _drush_bootstrap_drush() [0.01 sec, 2.32 MB] [bootstrap]
Loading drushrc "/Users/bwood/.drush/drushrc.php" into "home.drush" scope. [0.01 sec, 2.32 MB]             [bootstrap]
Cache HIT cid: 5.10.0-commandfiles-0-8f0556240f12135a37841fcdd2d6b529 [0.01 sec, 2.34 MB]                      [debug]
Bootstrap to phase 0. [0.04 sec, 7.45 MB]                                                                  [bootstrap]
Bootstrap to phase 0. [0.06 sec, 7.46 MB]                                                                  [bootstrap]
Found command: pantheon-auth (commandfile=terminus) [0.06 sec, 7.46 MB]                                    [bootstrap]
Cache HIT cid: terminus-last-email [0.09 sec, 7.5 MB]                                                          [debug]
Cache SET cid: terminus-last-email [0.09 sec, 7.5 MB]                                                          [debug]
Cache MISS cid: terminus-current-session [0.09 sec, 7.72 MB]                                                   [debug]
Pantheon dashboard password for bwood@berkeley.edu: Executing: stty -echo
Executing: stty echo

Authenticating as bwood@berkeley.edu [14.4 sec, 7.72 MB]                                                   [ok]
POSTing auth to: https://terminus.getpantheon.com/login [14.4 sec, 7.73 MB]                                   [notice]
Success! [17.09 sec, 7.73 MB]                                                                              [ok]
User UUID: a5814357-ecde-46aa-af6e-82336848c660 [17.09 sec, 7.74 MB]                                          [notice]
Cache SET cid: terminus-current-session [17.09 sec, 7.74 MB]                                                   [debug]




        .+.
        .+?:
         .+??.
           ??? .
           +???.
      +?????????=.
      .???????????.
      .????????????.

     ########### ########
     ############.#######.
     ####### ####  .......
     ######## #### #######                50 41 4E 54 48 45 4F 4E
     #########.####.######        _____________  __  ________  ____  ______
     ######  ...                 /_  __/ __/ _ \/  |/  /  _/ |/ / / / / __/
     #######.??.##########        / / / _// , _/ /|_/ // //    / /_/ /\ \
     #######~+??.#########       /_/ /___/_/|_/_/  /_/___/_/|_/\____/___/
     ########.??..
     #########.??.#######.
     #########.+?? ######.
               .+?.
         .????????????.
           +??????????,
            .????++++++.
              ????.
              .???,
               .~??.
                 .??
                  .?,.


LOGIN SUCCESSFUL.
Command dispatch complete [17.09 sec, 7.68 MB]                                                                [notice]
Peak memory usage was 9.27 MB [17.1 sec, 7.67 MB]                                                             [memory]
[bwood@mbp ~]$
```

**Comment by ari-gold** [comment]
I'm also having problem authenticating through UI and can authenticate with drush pauth.

**Comment by pirog** [comment]
@bwood i think you may have hit the nail on the head re: number of sites. 
@ari-gold (whats up man!) do you also have a ton of sites?

I would try to run 

$ drush ta --debug --verbose

and see what the output is. this is the actual command that is run on the kalabox ui side.

**Comment by ari-gold** [comment]
Hey @pirog! 

I only have one site with the new account that authenticates via drush but not in UI...

[ edited and removed output of drush ta --debug --verbose ]

**Comment by pirog** [comment]
Interesting... possibly a different issue than @bwood then. 

@ari-gold, do you have any special characters in your PW?

**Comment by ari-gold** [comment]
@pirog 

Yes, that was it. Generated password via KeePassX and have many special characters. I took out the " and it worked. 

Thanks!

**Comment by pirog** [comment]
Great! Awesome to know!

I'm not 100% sure if this is @bwood's issue. Let's wait to hear back from
him and if diff we can open a separate ticket.

On Mon, Jun 16, 2014 at 11:16 AM, ari-gold notifications@github.com wrote:

> @pirog https://github.com/pirog
> 
> Yes, that was it. Generated password via KeePassX and have many special
> characters. I took out the " and it worked.
> 
> Thanks!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kalamuna/kalabox/issues/8#issuecomment-46214236.

## 

Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by bwood** [comment]
Above I say:

> I even tried changing my Pantheon password to something containing just lower case letters.

so I don't think that's the cause of my issue.

**Comment by pirog** [comment]
@ari-gold can you open up another issue for the special characters " issue?

@bwood i _think_ this is just related to the amount of sites you have, as you theorized as well. does anyone else at berkeley have that many sites so you could test it out? might be good to know what the upper bound is here. 

In the meantime there are some things we can do on the kalabox side to make the requests to terminus less heavy.

**Comment by pirog** [comment]
@reynoldsalec terminuatur is a little bit too heavy when it tries to build out the terminatur alias file. we need a faster and more lightweight way to do this. i would check to see what requests we are making via terminus here
https://github.com/kalamuna/terminatur/blob/master/terminatur.bootstrap.inc

and whether we need to do all of them.

**Comment by reynoldsalec** [comment]
That makes sense @pirog. For my own edification, what was the reason that we needed to have separate terminatur aliases in the first place? Just to make sure we don't have the test/live environments available?

**Comment by pirog** [comment]
@reynoldsalec 
We add a bunch of meta data to these separate aliases so we can construct information like the path to the git repo or the rsync command. We keep them separate because pantheon aliases interact with pantheon sites and terminatur aliases interact locally. We also don't want to "hack" the pantheon alias file for all the normal reasons. 

What needs to be explored is whether we need to keep ALL the meta data that is being set as a resulted of making a request via terminus to the pantheon endpoint. 

@joshkoenig mentioned, as it related to switchboard, that we might be able to get additional information into the pantheon alias file to help with this so you could ask him. 

You could also generate this additional metadata when an actual operation is being performed on a site vs grabbing ALL of it when you authenticate. That would be a decent refactor but would def speed things up a lot.

**Comment by joshkoenig** [comment]
FYI - We have an issue in Terminus itself where building a new alias file for a user who's on the team for 100s of sites times out.

https://github.com/pantheon-systems/terminus/issues/153

We're looking at how to make these calls more efficient.

**Comment by pirog** [comment]
Thanks @joshkoenig that is great to know. 

Let's keep def keep an eye on/help with this terminus issue but also do what we can to make terminatur more performant as well.

**Comment by reynoldsalec** [comment]
FYI, added an issue for this in the terminatur queue: https://github.com/kalamuna/terminatur/issues/25

**Comment by pirog** [comment]
I've made this more efficient in terminatur which results in less requests to terminus. @bwood i am pushing out a development build of kalabox with this in it tonight if you want to try it out sometime. I'll post back when the release is out!

**Comment by pirog** [comment]
https://github.com/kalamuna/kalabox/releases/download/1.0-tango4/kalabox-1.0-dev.dmg
it will probably prompt you to update after you start it and say yes to that :)

**Comment by pirog** [comment]
I'm going to close this for now because im not sure there is much more we can do on our side but please let us know if it helps!

**Comment by bwood** [comment]
Just to report back.  I downloaded the dev version and I'm afraid that 
the problem remains for me.  I get "Unable to sign in.  Please check 
your credentials."

Brian Wood
Applications Programmer
UC Berkeley, IST/API

**Comment by pirog** [comment]
Ick... bummer. I think this might have to be resolved purely on the terminus end then. 

Can you paste the output of "cat ~/.kalabox/kalastack/config.json" here? Just want to verify it's all up to date!

**Comment by bwood** [comment]
Here you go:

```
[bwood@mbp openberkeley-drops-7]$ cat ~/.kalabox/kalastack/config.json
{
  "boxname": "kalabox",
  "boxuser": "vagrant",
  "kalastack_version": "3.0-beta4",
  "terminatur_version": "1.0-beta1",
  "puppet_environment": "deprecated",
  "default_memory": "2048",
  "memory_divisor": "4",
  "box_location": {
    "32": "http://files.kalamuna.com/kalabox32.box",
    "64": "http://files.kalamuna.com/kalabox64.box"
  },
  "ip": "1.3.3.7",
  "host_ip": "1.3.3.1",
  "host_entries": [
    "kala",
    "start.kala",
    "php.kala",
    "grind.kala",
    "solr.kala",
    "aliases.kala",
    "info.kala",
    "images.kala"
  ],
  "synced_www_folder": {
    "host_path": "/kalabox/www/",
    "guest_path": "/var/www/",
    "nfs": "true",
    "nfs_version": "3",
    "create": "true"
  },
  "ssh_forwarding": "false",
  "puppet_master": {
    "server": "kalabox.kalamuna.com"
  }
}
```
