### ISSUE TITLE
"No Realm Detected" when pulling site

### ISSUE THREAD

**Issue by aristomenis** [kalamuna/kalaboxv1#82]
Hello,
- Created a new site in Pantheon
- Spun up Kalabox
- Site showed with the grey cloud in Kalabox under "My Sites"
- Clicked it and chose download

Error:
"Request failed: 403 "No realm detected." [failed] Could not clone code from the remote repository. Check that your SSH key is loaded and the codeserver is reachable."

Verified that I could git clone the site from Kalabox's SSH - so no issue with SSH key, and codeserver is reachable.

Same error generated when trying:
drush pullsite mysite.dev --files

Tried updating aliases, but same error.

After a little spelunking, I found that the following fields were vacant in the terminatur.aliases.drushrc.php:
- uuid was missing
- uuid portion of db-url was missing
- uuid portion of git-connect string for code was missing

Not sure why this happened, but in case anyone comes across the same issue, here is the fix I used.
- Manually populated those entries
- Restarted Kalabox
- Clicked on site under My Sites to download
- All is well.

Cheers,
Ari

**Comment by pirog** [comment]
Thanks for posting this @aristomenis! 

@reynoldsalec @gremy it would be great to see if this UUID fail is happening for other people. anyone game to test? ill give it a try as well.

**Comment by aristomenis** [comment]
As an addendum, I'm able to consistently reproduce this at the moment.  Just now:
- Spun up new site in Pantheon (used Commerce Kickstart distro)
- Made a backup
- Started fresh Kalabox instance
- Refreshed sites in Kalabox... new site appears
- Click on grey cloud to download from latest backup

Error:
Request failed: 403 "No realm detected." [failed] Could not clone code from the remote repository. Check that your SSH key is loaded and the codeserver is reachable.

Looks like it is the uuid and uuid portion of git-connect missing.

terminatur.aliases.drushrc.php entry:

``` php
$aliases['my-kalabox-test.dev'] = array(
  'uri' => 'dev-my-kalabox-test.gotpantheon.com',
  'db-url' => 'mysql://pantheon:f314293a0a0d46a28298b374e886b284@dbserver.dev.7e36105b-7edf-4644-a4d0-4c661716b1cb.drush.in:13465/pantheon',
  'db-allows-remote' => TRUE,
  'remote-host' => 'appserver.dev.7e36105b-7edf-4644-a4d0-4c661716b1cb.drush.in',
  'remote-user' => 'dev.7e36105b-7edf-4644-a4d0-4c661716b1cb',
  'ssh-options' => '-p 2222 -o "AddressFamily inet" -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no',
  'path-aliases' => array(
    '%files' => 'code/sites/default/files',
    '%drush-script' => 'drush',
  ),
  'machine-name' => 'my-kalabox-test',
  'env' => 'dev',
  'uuid' => '',
  'built-from' => 'my-kalabox-test.dev',
  'terminatur' => array(
    'code' => array(
        'method' => 'git',
        'git-connect' => 'ssh://codeserver.dev.@codeserver.dev..drush.in:2222/~/repository.git',
    ),
    'database' => array(
        'db-user' => 'pantheon',
        'db-pass' => 'f314293a0a0d46a28298b374e886b284',
        'db-host' => 'dbserver.dev.7e36105b-7edf-4644-a4d0-4c661716b1cb.drush.in',
        'db-port' => '13465',
        'db-db' => 'pantheon',
        'local-db' => 'my_kalabox_test_kala',
        'method' => 'mysql',
        'download-bucket' => 'NONE',
    ),
    'files' => array(
        'method' => 'rsync',
        'rsync' => array(
                'options' => '-rlztv --ipv4',
                'ssh' => '-e \'ssh -p 2222 -o "AddressFamily inet" -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no\'',
                'excludes' => '--exclude \'js\' --exclude \'css\' --exclude \'ctools\' --exclude \'imagecache\' --exclude \'xmlsitemap\' --exclude \'backup_migrate\' --exclude \'styles\' --exclude \'less\'',
                'remote-files' => 'dev.7e36105b-7edf-4644-a4d0-4c661716b1cb@appserver.dev.7e36105b-7edf-4644-a4d0-4c661716b1cb.drush.in:files',
        ),
    ),
  ),
);
```

**Comment by pirog** [comment]
awesome! 
going to burn through the 1.x queue today so i'll have a chance to try and replicate this as well.

**Comment by pirog** [comment]
K, just spun up a fresh box and have all my UUIDs as expected. Will try your steps to replicate now.

**Comment by aristomenis** [comment]
Hmm, I wonder if something is garbaged up in my setup.

**Comment by aristomenis** [comment]
This was apparently related to the older beta install I had of Kalabox.  It had been running the "Updates Available", but apparently something didn't take or got glitched.  Did a fresh install with the latest beta download and this is no longer an issue.  Thanks!

**Comment by pirog** [comment]
This issue also seems resolvable by logging out and logging back in with your pantheon credentials either through the UI or with `drush ta` inside the box.

**Comment by ibuildit** [comment]
Pirog, that does not work for me. After a clean install of OSX, and installed Kalabox v1, I was able to download three sites OK, but on the fourth I got this issue, and I've tried EVERYTHING, and it doesn't work... something is very buggy here unfortunately.

**Comment by ibuildit** [comment]
And now I can't even restart the box.

![screenshot 2014-09-20 19 57 52](https://cloud.githubusercontent.com/assets/5072873/4346134/c5f4dde2-40ef-11e4-954a-5b80c653a4bf.png)
![screenshot 2014-09-20 19 58 43](https://cloud.githubusercontent.com/assets/5072873/4346133/c5df3cf8-40ef-11e4-904c-956920a1d2c2.png)

**Comment by ibuildit** [comment]
It seems that sometimes, a random process of clearing drush cache via drush cc drush and clearing the drush cache dir, rebooting the box, logging in and out, deleting keys from pantheon, etc can make it work again, for an unknown period of time before it suddenly happens again.

**Comment by ibuildit** [comment]
After an uninstall, and reinstall, the first thing that happens is that:

1: I can't select a backup from Pantheon until after the first attempt to download.
2: After I choose to take the latest backup, it starts to spin for a while, downloads the code and the database but does not create any vhosts, and then the same message box pops up again:
![screenshot 2014-09-20 20 09 13](https://cloud.githubusercontent.com/assets/5072873/4346173/3f103db0-40f1-11e4-9210-82df593d9d47.png)

If I try to do it again, the same thing happens.

**Comment by ibuildit** [comment]
Kalastack works perfect though, except it doesn't make the hostsfile changes.

**Comment by ibuildit** [comment]
Except... when it doesn't... i get the same thing in kalastack now.

**Comment by ibuildit** [comment]
But I can confirm that adding the uuid manually makes it work again. It appears random WHEN it occurs though.

**Comment by pirog** [comment]
it might be worth checking on the pantheon side to see if there is anything
happening over there

On Sun, Sep 21, 2014 at 2:49 PM, ibuildit notifications@github.com wrote:

> But I can confirm that adding the uuid manually makes it work again. It
> appears random WHEN it occurs though.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kalamuna/kalaboxv1/issues/82#issuecomment-56314028.

## 

Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by mmenavas** [comment]
I just ran into this issue. In my case only the UUID was missing in terminatur.aliases.drushrc.php. Manually populating this value fixed the issue.

**Comment by pirog** [comment]
MAXIMO!

the UUID comes from a terminus API call. I think maybe in some circumstances based likely on organizational permissions on the pantheon end these ID's are not available to all team members. i know @andrewmallis experienced this on the badcamp site as well. 

maybe @joshkoenig has some insight?

**Comment by mmenavas** [comment]
@pirog Thank you for the quick response =)

**Comment by labboy0276** [comment]
I all of a sudden started having this issue as well, only on new sites I just made

Issue references here:
https://github.com/pantheon-systems/terminus/issues/148

I tried updating my terminus only and it didnt fix it

**Comment by joshkoenig** [comment]
Hey All,

I'll see what I can see. That terminus issue is pretty stale but we can take a look.

@labboy0276 can you see if the site uuid is missing from your drush alias? 
@pirog is it possible to have Kalabox run terminus with the `-v -d` flags so we can capture mass debugging output?

**Comment by joshkoenig** [comment]
@pirog @andrewmallis there isn't a case where a user wouldn't have access to the site UUID, though making a specific API call for just that seems inefficient. Can you give me a bit more context on where/when this call is being made?

Also cc @mikevanwinkle ;)

**Comment by labboy0276** [comment]
@joshkoenig Yes it was, I saw that above.  So I did a couple thingz.  I looked at ~/.ssh in my stack and grabbed that authorized_key and put it into pantheon.  Then I ended up doing was this in my stack:

``` bash
$ cd /etc/drush
$ rm -f terminatur.aliases.drushrc.php
$ drush ta
```

It populated all my uuid's for all my sites & all is well.  Game on

**Comment by pirog** [comment]
This is all great data!

On Tuesday, October 14, 2014, John Ouellet notifications@github.com wrote:

> @joshkoenig https://github.com/joshkoenig Yes it was, I saw that above.
> So I did a couple thingz. I looked at ~/.ssh in my stack and grabbed that
> authorized_key and put it into pantheon. Then I ended up doing was this in
> my stack:
> 
> $ cd /etc/drush$ rm -f terminatur.aliases.drushrc.php$ drush ta
> 
> It populated all my uuid's for all my sites & all is well. Game on
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kalamuna/kalaboxv1/issues/82#issuecomment-59075458.

## 

Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by joshkoenig** [comment]
Got it. We should figure out how to make the `drush ta` (terminatur aliases I presume) work more reliably. Sounds like there's some room for failure there.

**Comment by pirog** [comment]
Agreed. Been on the docket for awhile but alas THE THINGS.

Instead of fixing up terminatur it may make more sense and would be more
ambitious to swap it out for the @fluxsauce switchboard project which is
what we are using in KALABOX 2.

On Tuesday, October 14, 2014, Josh Koenig notifications@github.com wrote:

> Got it. We should figure out how to make the drush ta (terminatur aliases
> I presume) work more reliably. Sounds like there's some room for failure
> there.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kalamuna/kalaboxv1/issues/82#issuecomment-59075949.

## 

Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by andrewmallis** [comment]
I can confirm the missing UUIDs + same symptoms described above have plagued me, and the resolution by @labboy0276 to regenerate terminatur.aliases.drushrc.php solves the problem.

**Comment by pirog** [comment]
OHHHH ... I think I might have my finger on the pulse of this one now.

Will try out in a sec and report back

On Tuesday, October 14, 2014, Andrew_Mallis notifications@github.com
wrote:

> I can confirm the missing UUIDs + same symptoms described above have
> plagued me, and the resolution by @labboy0276
> https://github.com/labboy0276 to regenerate
> terminatur.aliases.drushrc.php solves the problem.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kalamuna/kalaboxv1/issues/82#issuecomment-59078751.

## 

Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by snowguy** [comment]
Like andrewmallils, I had the same symptoms and @labboy0276  's resolution worked. Am using the latest version of kalastack.

**Comment by ibuildit** [comment]
I will repeat the last post... Like andrewmallils, I had the same symptoms and @labboy0276 's resolution worked. Am using the latest version of kalastack.

**Comment by dboeger** [comment]
I'm not sure if this is tied to this issue or not, but this is what I was experiencing on the issue #156 referenced by reynoldsalec.  I can't get kalabox to start up at all.  Everytime I try I get this window.

![screen shot 2015-07-07 at 2 22 43 pm](https://cloud.githubusercontent.com/assets/2817897/8557681/ced59aac-24b3-11e5-954d-cc897a97b680.png)
