### ISSUE TITLE
Remove kalabox64.box in Uninstall Script

### ISSUE THREAD

**Issue by reynoldsalec** [kalamuna/kalaboxv1#9]
Occasionally the box image is corrupted on download; perhaps we should have an additional option (or include it in the complete wipe option) in the uninstall script to delete that as well?

Suggestion via Will Hise.

**Comment by pirog** [comment]
Good call. I think an option would be good. 

There are a lot of minor improvements in the issue queue here and over in the kalastack so im thinking about maybe rolling a new beta6 release sometime next week.

**Comment by reynoldsalec** [comment]
That should do this guy.
