### ISSUE TITLE
Stuck on installing..

### ISSUE THREAD

**Issue by sbilde** [kalamuna/kalaboxv1#99]
Trying the kalabox v.1, but im getting the following error in the log: http://d.pr/i/EotN

Could someone point me in the right direction, so I can test this magic box I have heard so much about;)

/Steffen

**Comment by pirog** [comment]
check this issue out. seems to be the same... lets consolidate 
https://github.com/kalamuna/kalabox/issues/98

**Comment by sbilde** [comment]
Thanks Mike..- Seems to be working after deleting the keychain value:
http://d.pr/i/9zMF

Coooool :)

2014-07-29 18:32 GMT+02:00 Mike Pirog notifications@github.com:

**Comment by pirog** [comment]
Great! could you post this over on #98?
